### ISSUE TITLE
Multiple records in the same TextBox

### ISSUE THREAD

**Issue by armansansd** [berteh/ScribusGenerator#100]
Hi, 
I'm using this script on Scribus in order to create a leaflet for a festival. I have a few questions, after running some test I would like to know if it is possible to create multiple record in the same text box ? And does it creates automatically pages when it reaches the end of the bloc ?

Thank you very much , 

cheers :)

**Comment by berteh** [comment]
Hello.

Yes you can put multiple records in a single box using the %VAR_NEXT-RECORD% tag (which needs to be on its own line in your text box), more info at https://github.com/berteh/ScribusGenerator#multiple-records-on-a-single-page

No, a new page is not created automatically when end of block is reached, instead the "default" behavior of Scribus when a text overlaps the available space is to hide it, and display an error in the preview before printing/exporting dialog, pinpointing to the problematic text box.

If you believe this feature is important feel free to explain to me shortly how I could distinguish the boxes that should trigger a new page and those that don't (for instance if you want to preserve your layout)... and how you would detect an overlap (I don't think this info is available in the API.. and even less in the SLA source file).  If you feel like it you can as well implement it and send a pull request, I'd have a look and would gladly integrate into next release !

Thanks for your interest !
Berteh.

**Comment by berteh** [comment]
ok thanks.
