### ISSUE TITLE
Text linking only works for 90 items?

### ISSUE THREAD

**Issue by adamwolf** [berteh/ScribusGenerator#101]
I have a template and a data file with about 300 items.  I have multiple text frames that some data flows into via linking.

It works fine for the first 90 data entries, and then stops overflowing into the second text frame after that! It shows up as an overflowed text frame, and it doesn't seem to know that it's linked to the second frame of that page.  I can link it manually, and it works fine, but I don't want to link literally thousands by hand.

Any thoughts?

**Comment by adamwolf** [comment]
I changed the sorting on the CSV file to see if there was something magical about the data in line 90, and even after the contents changed, it still happened at line 90.

**Comment by jvr14115** [comment]
not sure what you mean by "overflowing in the 2nd text frame". I would be happy to take a look. Any chance to post the template and the csv?

**Comment by adamwolf** [comment]
I will see if I can dig it up.  Thanks!

**Comment by berteh** [comment]
Hello @adamwolf 
This problem should be fixed now. Am I correct in assuming you had the problem only in the "merge" output mode?
Have a nice day.
Berteh.

**Comment by adamwolf** [comment]
Works great!  Thanks!

**Comment by berteh** [comment]
You're welcome.

@jvr14115  Jeroen, in this fix I just "delayed" the problem. If someone was to generate a document with more than 100 000 linked frames the same problem would happen again. If you have any idea how to compute unique ID number for each new generated text frame, is linked successor (if any) and its linked predecessor (if any) that would be great !

**Comment by berteh** [comment]
@jvr14115 let me know if you want to work on this. I'd then reopen the issue and assign it to you.
