### ISSUE TITLE
Images/Data/Output folders

### ISSUE THREAD

**Issue by jvr14115** [berteh/ScribusGenerator#102]
Hi Berteh,

I thought to have found a sollution but unfortunately...

I have images in several folders on drive A.
The Scribus template is on drive B in folder 1.
The csv data is in on Drive B in folder 2.
The outputs should go to Drive B in folder 3.
(folders 1,2 & 3 are different folders in the same main folder).

I tried virtually every possibility to get this working.
The data file is found, text data is working fine and output goes in the intended folder.
Only issue is I dont get Generator/Scribus to pull the images.
I added the full path in the csv. Even with testing to put all images in a folder 4 on drive B, it wont work.

What am I doing wrong?

**Comment by berteh** [comment]
hello @jvr14115 

AFAIK Scribus handles images with relative addresses, not absolute, so you'd have to be sure the depths of your images stored in A/ is the same from B/1 and B/3.  
I'd try to check out a few things in your circumstance:

1. When you include one of your images in the SLA template document does it show? If not it may be a user access rights or file format issue.

2. Try to copy-paste one of the generated SLA files in your template folder (B/1), and open it. 
-> If this displays the images correctly you can fix the problem by adding linked directories that make the paths depth match.
-> If not it could mean the combination of output directory (B/3) + file path in CSV data does not point to an existing image. It may be a problem of the different drive, as no such thing exists in Linux I may have not tested this. I usually create a symbolic link ([how-to in windows](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/), in linux or mac run the ``ln -s <target> <name> command``) that points  to my resources on a another drive to access them "localy" from within my project... and guess this should work for you: I would 
a) create in B/1/ a symbolic link called "img" targeting A/path-to-images-root/
b) create in B/3/ a symbolic link called "img" targeting A/path-to-images-root/
c) in my template include the image located in B/1/img/%VAR_pic1%, and  B/1/img/%VAR_pic2%
d) set the variables ``pic1`` and ``pic2``  in your csv to any subdirectory + file name EXCLUDING A/path-to-images-root/

for instance if you have images in
A:\user\emil\library1\sunset.jpg
A:\user\emil\library1\moonset.jpg
A:\shared\jetski.jpg
A:\shared\diving.jpg

your "img" symbolic links would target "A:\", as there is no other subdirectory all your images have in common, and your csv data would look like:
pic1|

For my info: what is your OS: Win/Mac/Linux?

**Comment by jvr14115** [comment]
Hi Berteh
Thanks for your quick response and good advice.

I am not really sure why it works, but it does:
Apperently the 1st image you put in a document "fixes" a path.
So the sollution I no use is to place a first image from c:\. Then replace that image by a %VAR_something%.
In the CSV, I put the full path of each image excluding "C:\"
Seems to work perfectly.
By the way: it does not matter if you put / or \ as directory sign. Both will work.
In my case all images are on C:\ so I do not need to make any virtual lyncs or shortcuts.

Thanks again.

**Comment by berteh** [comment]
glad it worked for you.

Could you please have a quick look at the related section in the document and tell me how I could improve that bit to make it more clear for the other users if they run into the same kind of troubles?
It's located at https://github.com/berteh/ScribusGenerator/#dynamic-images

thanks.
Berteh.

PS: if you have a template or generated document you're particularly proud of don't hesitate to share it with other users, for their inspiration, in https://github.com/berteh/ScribusGenerator/wiki#gallery-of-examples--some-templates

**Comment by berteh** [comment]
Good suggestion, thanks!

If you have a hack don't hesitate to submit it as pull request. Otherwise I
put it on my to-do list... but not for the next days.

B.

**Comment by berteh** [comment]
Hello @jvr14115 
SG now supports the use of subdirectories in the output file name. Combine it anyway you like with variables from your data set. Hope this works for you... more info at https://github.com/berteh/ScribusGenerator#dynamic-output-file-location
B.

**Comment by berteh** [comment]
nice idea. will try to integrate in the plugin menu. thanks for the suggestion.
