### ISSUE TITLE
Syntax Error in file ..Backend.py under Python 3.6

### ISSUE THREAD

**Issue by rotor-head** [berteh/ScribusGenerator#103]
I'm seeing the nightmare that is Apple macOS support of python in the threads. As such, I'm stepping through using Macports version 3.6.x build for all the goodness of the most recent version of python. Macports offers to update the env for use of python 3.6 along with the additional modules as needed. It doesn't touch the antiquated Apple build. 

From what I can glean here, running on a Mac doesn't have any bearing on this issue.

Here's what I'm seeing prior to modifying Backend.py:
$ ./ScribusGenerator.py
Traceback (most recent call last):
  File "./ScribusGenerator.py", line 22, in <module>
    import ScribusGeneratorBackend
  File "/Users/Erich/lib/ScribusGeneratorBackend.py", line 496
   ` except SyntaxError, e:`
                               `^`

Changing two lines with
   `except SyntaxError as exception:`  
corrects the error and the script continues without issue.

From what I'm gathering through searches, python 3.6 brings changes to the syntax of the exception - dropping the comma in favor of the keyword  'as' ... not sure if the shorthand 'e' is still viable - I went ahead and typed out the full word.

**Comment by berteh** [comment]
thanks for the report. Changed accordingly.
