### ISSUE TITLE
macOS Sierra and Tkinter (or is it tkinter?)

### ISSUE THREAD

**Issue by rotor-head** [berteh/ScribusGenerator#104]
Just adding some color to the discoveries around Python 3.6 and Tkinter. 

I ran the gui test from an earlier post regarding another macOS user struggling to fix Apple's complacency. The error: module Tkinter not found lead me to think there might be a namespace issue.

`#!/usr/bin/env python
import tkinter
from tkinter import Frame, LabelFrame, Label, Entry, Button, StringVar, OptionMenu, Checkbutton, IntVar, DISABLED, NORMAL, PhotoImage
tkinter._test() # a small windows with 2 buttons should pop up. It may be located under the current application.`

Modifying the Tkinter entry in the script to all lowercase, tkinter loaded the test via X11 interface.

This is most likely something to do with the Macports build using a different convention for the name, however, I thought I'd document this for others seeking to take advantage of this great script.

**Comment by rotor-head** [comment]
Well, running the script within Scribus throws an error that the module tkinter was not found. Modifying back to Tkinter gets us a little further. Running from bash errors out.

**Comment by berteh** [comment]
Thanks   @rotor-head for trying hard to figure this out. Did you get satisfactory results in trying to run the GUI on Mac?   

The GUI is indeed meant to be run from within Scribus, and I guess it thus loads the librairies linked to by Scribus.
The CLI version of ScribusGenerator is meant to be run standalone, thus independently from Scribus, and is reported to work with the stock Python available in Mac, as far as I know.

**Comment by rotor-head** [comment]
A LOT of tinkering with the GUI and Mac ports but had a project due and resorted to the CLI. I did encounter an issue with the CLI and will submit a ticket.

Erich

**Comment by berteh** [comment]
I'll reopen this bug as a placeholder to discuss how to make the GUI work in Mac OS X. Could you give us any pointer how to test / make this work ?

**Comment by rotor-head** [comment]
I will say, part of my challenge in tracking this down is my lack of Python experience. Testing has been the one obstacle I haven't been able to overcome. 

First issue testing via the command line is that python calls the scribus module, that is only available from within Scribus. That's when the script stops. I can't get any output in the log file. I went so far as to modify a debug wrapper found on Scribus but even that errors out (debug-wrapper.py) within Scribus. My first runs using the testing scripts you provided via the command line were giving results. At one point, I removed the Macports version of Python, did reboot, and then re-installed py27 along with the dependencies. The camel case issue resolved and the test scripts ran w/o modifying the module names.

Using the Macports to install Python 2.7 along will all the dependencies it appears the Macport roll out changes the current bash env to use the new install. However, system links to the upstream provider install is left untouched. I think there are other env variables in the system that still refer back to the shipped build of python versus using the Macports installation. And this is likely why scripts end up failing. Again, without any debug or logging available, it's impossible to know.

My latest effort was to install Qt5 and CMAKE a debug build of Scribus in an effort to get any output. That simply lead to more issues attempting to get a build that actually loaded. The computer I'm using has been through four OS upgrades. It's not exactly a pristine base.

The Macport version of Scribus (which DOES NOT run on Sierra by the way) also builds and installs python into the same directory as Scribus. This is more evidence to me the issue revolves around getting a free and clear instance of python 2.7 running for the entire system. That's just speculation at this point. The other point here is the script IS CLEARLY NOT the problem.

**Comment by berteh** [comment]
thanks for trying  @rotor-head . Sorry to read it did not work. I cannot help you more as I don't own a Mac.

I've had reports of other users using ScribusGenerator from the command line just fine on Mac. But never the GUI, that is for sure... as you've experienced.
