### ISSUE TITLE
Py file not running in Scribus

### ISSUE THREAD

**Issue by Jamcob** [berteh/ScribusGenerator#108]
I'm running OSX 10.11 and Scribus 1.5.2

I can almost guarantee I'm missing a step here.

I've installed Scribus, Python and downloaded Scribus Generator.

Do I need to be doing something with TKinter?

Whenever I try to run the script nothing happens, with no access to any dialog boxes to load up my csv files. 

Thanks

**Comment by berteh** [comment]
Hello @Jamcob 

I've had several reports of problems to run this script with its graphical interface on Mac, but the [command line interface](https://github.com/berteh/ScribusGenerator/blob/master/README.md#running-scribus-generator-from-the-command-line), on the other hand, works just fine on that OS.

See the README, or our [wiki page](https://github.com/berteh/ScribusGenerator/wiki/Running-Scribus-Generator-from-the-command-line) to get info on who to run the command line version of Scribus Generator.

If you find a way to make the GUI run in Mac OSX that would be great. This point is being discussed in issue #104
