### ISSUE TITLE
YPOS

### ISSUE THREAD

**Issue by jonnydrake** [berteh/ScribusGenerator#109]
Hello,
I'm working with this Software and it makes a lot of fun.
But I have a Problem with the SGAttribute YPOS. Is this just working with Points (pt) or is there a way to use it with the Unit: mm Millimeters (mm)? This would be nice!

But I couldn’t run it that way. So I switched the Unit to Points (pt). Then I took the value from the properties box (X,Y,Z / Y-POS) but the Text Frame was not on the right Position. It was a view Points higher. So using the value form Scribus 1.4.6 in my csv doesn't work.

Do I miss something or has someone similar problems?

**Comment by berteh** [comment]
Hello Jonny.
Thanks for getting in touch, nice to read you're having fun with Scribus Generator.

I did not get in depths for each attribute but will look at YPOS in more details. So far my approach was a quick'n dirty "test and manually correct the CSV data when needed"... but I'll try to find out how the internals of Scribus work on this. If i remembered correctly all POS units are internally converted by Scribus into Points... but the available documentation does not say much: 

-  https://wiki.scribus.net/canvas/File_Format_Specification_for_Scribus_1.4#Tags
-  https://wiki.scribus.net/canvas/(FR)_Introdution_au_Format_de_fichier_SLA_pour_Scribus_1.4 (bit more explicit if you read french)

Could you attach your template and (opt. partial) dataset for test purposes in a reply to this issue, if it's not confidential?

**Comment by berteh** [comment]
I forgot to ask: 

1. are you generating separate documents for each data line, or using the merge/simple output mode ?
1. How many pages does your template contain? (for multiple pages may induce other issues with POS values computation)

**Comment by berteh** [comment]
You are right. Understanding how Scribus handles YPOS is a mess. I'll keep looking at it... but don't know if I'll figure it out. If you have any idea how they make it kindly share your ideas ! It sometimes seems to be relative to active page ( eg when you move an object in its page), sometimes relative to whole document...

In the meantime I noticed the current ways of using SGAttributes is no longer possible in Scribus 1.5.3 since the GUI was "improved" by restricting the "Type" of Attributes. I thus had to slightly change the syntax of the Attributes, as explaine in https://github.com/berteh/ScribusGenerator#changes-in-sgattribute-syntax  ... Please update your template accordingly ([a script](https://github.com/berteh/ScribusGenerator/blob/master/ConvertSGAttributesToSG27.py) is also provided to do it automatically if you have many SGAttributes)

**Comment by berteh** [comment]
test template and data... if you wanna play with it you're welcome to help me figure out how Scribus actually handles YPOS and XPOS values... maybe there is another attribute involved in their interpretation?

[dynamicYPOS.zip](https://github.com/berteh/ScribusGenerator/files/1935150/dynamicYPOS.zip)

**Comment by jonnydrake** [comment]
Thank you very much for the answers and the dynamicYPos.zip
So the result of playing around is:
I added for xpos: +100 and for ypos: +20
In the Attachment I simplified your test template.
1. removed the ] from the text in the text frame %VAR_id% x:%VAR_xpos%  y:%VAR_ypos%
The CSV contains two lines.
xpos (in csv) 184 = xpos (Scribus) 84
ypos (in csv) 60 = ypos (Scribus) 40
ypos (in csv) 120 = ypos (Scribus) 100

Answers to your questions:
are you generating separate documents for each data line, or using the merge/simple output mode ?
- Yes I'm generating separate PDF's for each data line.

How many pages does your template contain? (for multiple pages may induce other issues with POS values computation)
- I'm working with a single page document.
[dynamicYPOS_v02.zip](https://github.com/berteh/ScribusGenerator/files/1937460/dynamicYPOS_v02.zip)

**Comment by jvr14115** [comment]
I am really struggling with Xpos.
Currently I switched back to working from 1.5.2 version.
I have a csv with "Xpos" and values in points. For testing purposes it only has 2 lines.
When I set the Attribute as Name:XPOS, Value: %VAR_Xpos%, Type:SGAttribute, Paremeter:null
nothing happens
When I set the Attribute as Name:XPOS, Value %VAR_Xpos%, Type:null, Parameter: SGAttribute
The object is place on a position which I cannot understand. More important: it places the object on the same position for both records. (I tried merge and single mode.).

Help would be much appreciated.

**Comment by jvr14115** [comment]
ok. this seems to be working:
Name:XPOS, Value %VAR_pos%, Type: SGAattribute, Parameter: SGAttribute
Now I need to figure out how these points need to be calculated. It seems 100 is around 0...

**Comment by jvr14115** [comment]
So 100 seems to be the 0 position.
1 mm is about 2.835 pts.

I am using the Xpos to create a catalogue and offset the left and right pages for the gutter: move a left page 2mm left and a right page 2mm to the right.
- I created a template that creates single pages. with a 5 mm bleed and let SGI create single sla files.
- a 2nd template (same size, also with a 5mm bleed) holds an image frame over the full size of the page + bleeds. via SG I create a merged pdf importing the single sla file.
Works like a charm and beats creating left and right pages in the original template.

**Comment by jonnydrake** [comment]
@jvr14115
Xpos 100 is 0 and
Ypos 20 is 0

**Comment by berteh** [comment]
thanks @jonnydrake ah, this is so logic, why didn't I figure it our sooner :/

**Comment by jonnydrake** [comment]
Solved
Thank you very much.
