### ISSUE TITLE
command line (opt.) use partial data, only from:

### ISSUE THREAD

**Issue by jonnydrake** [berteh/ScribusGenerator#110]
Hello,

I searched the Wiki and the issues but I don't know how to create a specific data.
In the script there is the Option: (opt.) use partial data, only from
Is there a command line Option?

**Comment by berteh** [comment]
Hello @jonnydrake 
I don't exactly understand your question.

Partial data is meant to generate your documents using only some lines in your CSV files, not all.
Let's say your CSV file contains 200 lines, you can feed the Scribus Generator with only a subset of these, for instance the 20 lines starting at the 121th record.

Using the GUI it is done by setting some value in ``from``, for instance 121, and ``to``, for instance 140. 
Using the command line (look at the [documentation](https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line)), simply use the corresponding options: 

    -from 121 -to 140

**Comment by berteh** [comment]
did this solve your problem ?

**Comment by jonnydrake** [comment]
Yes thank you.
