### ISSUE TITLE
Scribus Multiple Duplicate feature creates parsing issue

### ISSUE THREAD

**Issue by rotor-head** [berteh/ScribusGenerator#111]
I'm pulling names, email, business name, and industry info from a CSV file to iterate out on a page. This is the third time I've used the template but had made a change in one of the variables (wanted to bold the person's name.) the list is 30 lines long on a single page, so it requires 30 entries for the variables.

Having to copy-n-paste is so tedious, then I found the Multiple Duplicate feature in Scribus. For the record, I'm not feeling like copy-n-paste is so tedious now. Here's why:

When running the merge from the command line (I'm on a Mac, it's the only way) the data from the first record is truncated after the first two fields and combined with the next record's remaining fields. I invested a good two hours massaging the CSV file out of a desire to get it working.

CSV example:

firstName, lastName, email
Barney,Fife,fife@mayberry.org
Thor,Hammer,bighammer@hammers-r-us.eu
Tony,Stark,imsorich@tstark-enterprises.com

The resulting merge appears as:

Barney Fife bighammer@hammers-r-us.eu
Thor Hammer imsorich@tstark-enterprises.com
Tony Stark etc ....

Not sure if this is something that can be addressed within the Generator as it appears to be more of an issue with Scribus. However, it would be very nice to be able to apply a merge cleanly, especially if we're looking at hundreds of records to merge.

**Comment by berteh** [comment]
Hello Erich.

Looks to me like the "next record" token kicks in before the last variables
of the line are substituted with the current values.

I'll have to look at it more thoroughly, but a quick workaround could be to
move your "next record" tag at the *beginning* of each block instead of
putting it at the end of the last line, where I guess it is. Of course, in
this case, you should not have any "next record" in the very first block.

Another workaround could be to put your "next record" on a new line of
text, not at the end of a text block where other text needs to be
substituted.

Kindly let me know how this goes for you.

Better.

**Comment by rotor-head** [comment]
So, that idea works.

The CVS has:
[Header]ID,FirstName,LastName,email
,,, <---- not sure why I have to create this empty set, but the merge fails without it.
[FirstDataRow]
[SecondDataRow]
[etc]

The following line is created in Scribus, then, using the Multiple Duplicate routine, the exact same number of items found in the CVS minus one, are created.
%VAR_NEXT-RECORD% %VAR_ID%:  %VAR_FirstName% %VAR_LastName%  %VAR_email%

And the output builds as desired.

That's perfect for me.

On a side note, I did attempt leaving the %VAR_NEXT-RECORD% out of the first row in the template file, but the merge failed with an error.

**Comment by VynceMontgomery** [comment]
Yeah, this appears unrelated to the "multiple duplicate" feature. 

Note that loading the next record happens at [Line 433](https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L433) and the data substitution doesn't happen until [Line 444](https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L444). So, if your next-record call happens in a line with variable substitutions, they will be from the new record, even if they appear earlier on that line. As such, you can either put the NR call at the "beginning" (lowest layer) of the next template or as its own element, in which case it doesn't, in some sense, matter whether it's the last item in the old template or the first element in the new one; it's a template separator.

**Comment by berteh** [comment]
thanks @VynceMontgomery for kickin' in ;)
more info on the next-record usage is available at https://github.com/berteh/ScribusGenerator/wiki/How-to-use-%25SG_NEXT-RECORD%25

feel free to improve that bit of documentation with more insights... as it is currently quite difficult to use, unfortunately.
