### ISSUE TITLE
Line feed from CSV file field

### ISSUE THREAD

**Issue by vassagoqc** [berteh/ScribusGenerator#114]
Good day,

dont know if it's the right place to ask this, but, i'm trying to have line feed from a specific field when merging my CSV file with Scribus.
I've read the doc and try many test, but could not get a good result.
As an exemple, if my CSV has 2 fields like this 

name, colors
Bob, Green\nRed
Paul, Green\nRed\nBlue

How can the colors field be listed inside my textbox, like a bullet list for exemple.

By the way, this script is awesome.

Many Thanks.

**Comment by berteh** [comment]
Hello.
Glad you like the script.

Linebreaks and tabulations in your CSV data are currently replaced by the scribus equivalent (newlines and tabulations)... Or you can decide to remove them and turning them to simple spaces set the setting KEEP_TAB_LINEBREAK to 0.

So, it won't show as a bullet list yet, but maybe we can find a way to improve the script in this direction. I'd rather not simply replace all linefeeds in CSV by bullet lists... as that may not suit everyone, but rather (in the idea of Markdown) a combination of "\n- ". 

If you feel like forking the code and trying to improve the code in this direction I'd gladly help/review your contribution. It happens around https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L459

Leet me know, and have a nice day,
Berteh.

**Comment by berteh** [comment]
This could also take the direction of integrating (partial) markdown import, if you have such an interest.

Or you can just use any UTF character that would display as a nice bullet directly in your CSV. This character _needs to be supported by the font in use_. Some examples:
Paul," • Green\n  • Red\n  • Blue" , 
Bob," ● Green\n  ↝ Red\n  ∘ Blue\n, 😀Green\n 🚙 Red\n ✔Blue" , 

Just copy-past the utf-8 symbol from any characters table on the internet, like https://unicode-table.com/en/#emoticons... and make sure you save your CSV as UTF-8.

Or you could another script after the merge, such as [bullets](https://wiki.scribus.net/canvas/Bullets), or [bullets and numbered lists](https://wiki.scribus.net/canvas/Bullets_and_numbered_lists). Never tried them but they seem to do the job.

**Comment by cummingsrob** [comment]
I'm also having a problem getting the linefeed to work correctly. I've tried a couple different tests, but in each one it's printing the \n. The \n is not replaced with the linefeed. Using the ScribusGenerator-python3 version. Thoughts?

**Comment by berteh** [comment]
Hi Rob.

Are you maybe writing "\n" in your CSV? As in a backslash character and a 'n' character?

If that's the case then sorry for not making the documentation more explicit: your should simply use a real line feed character ('enter' or 'return'). The CSV should look like the `examples/business-card.csv` file, have a look eg at the line below, where the data with a newline must be quoted:

    Rachel Banks,"Expert
    
    Assistant",


This should get properly replaced by ScribusGenerator into a linefeed Tag. If not please kindly tell me your OS and Scribus version. I'll look into it further.

Hope it helps.
Berteh.

**Comment by berteh** [comment]
PS: just ran the "business cards" example in scribus 1.5.6.1 (with python3 script version), and it seems to work fine on linux:
![image](https://user-images.githubusercontent.com/36950/158013931-60814061-a193-4cc5-847e-f1f57686115f.png)

... so kindly send me your CSV as attachment if you can confirm the problem.

**Comment by cummingsrob** [comment]
I was writing the "\n" right in the spreadsheet and exporting that to the
csv. I thought the script replaced that string with an actual linefeed.
Adding it to the cell using Alt-Enter in Google Sheets works perfectly. The
exported csv look exactly like your example. I'll continue doing that.
Thank you so much for your help. This script is great!

**Comment by berteh** [comment]
You're welcome.
Feedback's always welcome, and showcasing what you did with it as well, directly in the wiki: https://github.com/berteh/ScribusGenerator/wiki
