### ISSUE TITLE
script to collect all variables in a csv

### ISSUE THREAD

**Issue by jvr14115** [berteh/ScribusGenerator#116]
not an issue but a contribution.

I have a couple of templates with a lot of variables that are filled by databases.
To make my life easier and to keep track of all variables (+check if I named them right), I created a small script that will create a CSV containing all the variable fields (text & image frames only, no attributes)
Hope it is usefull.
I suppose with a little modification it could also be used to create the table to fill in the data.

Script:

## CSV is stored in same folder with the suffix 'Elements'

import os
import re

Edoc=scribus.getDocName()
Edoc=Edoc.replace('.sla','')
file_name=Edoc+'Elements.csv'
Edoc=Edoc.replace('Elements.csv','')
Edoc=re.search(r'(.*)/(.*)',Edoc).group(2)
f=open(file_name,'w+')
f.write('Template,Element,ElementType')
f.write('\n')
objL = scribus.getAllObjects()
for obj in objL:
	objT=scribus.getObjectType(obj)
	Evar=''
	if objT=='ImageFrame':
		Etype='image'
		Evar=scribus.getImageFile(obj)
	if objT=='TextFrame':
		Etype='text'
		Evar=scribus.getAllText(obj)
	if '%VAR_' in Evar:
		Evar=re.sub('^[^%VAR_]*%VAR_', '',Evar)
		Evar=Evar[:-1]
		f.write (Edoc+','+Evar+','+Etype+'\n')
f.close

**Comment by berteh** [comment]
Thanks. It's now included in ``script/`` folder.
