### ISSUE TITLE
What is the "last field" after which I put the var next record?

### ISSUE THREAD

**Issue by UltraSalem** [berteh/ScribusGenerator#117]
I'm making game cards with multiple elements all over the template created at different times. Which is the "last field"? The lowest in the template? The right most? The one on the highest layer? The one created last? (Which I don't know now as I've been renaming them all to something useful). I tried creating a new text field of %VAR_next-record% at the bottom right of the template but it didn't seem to think it was really the last field. So I was getting half of one row of the CSV in the template and then half of the next row. The SLA is "vanguard_units.sla" in here https://gitlab.com/blkjck/kow_player_aids

**Comment by UltraSalem** [comment]
Nevermind, I worked it out. It's level height. :)

1) Build your card and card back once. 
2) Ensure a text box appears on the card somewhere containing "%VAR_NEXT-RECORD%".
3) Raise the %VAR_NEXT-RECORD% text box to be **the highest level** using the up arrow in the properties box.
4) Select all and group all the card elements together.
5) Item menu -> multiple duplicate. Make it repeat an additional 3 times to fill the page with 4 cards. 1.5mm vertical gap.
6) Select each card group and ungroup them in turn.
7) Remove the %VAR_NEXT-RECORD% text box from the last card. The script knows to go to the next record at the end of the single page automatically.

For some reason it gets all wonky if the card elements are still grouped when running the script, output only starting half way down the first page, and every other page was blank.

Thanks for an awesome script! And sorry for my dumb question.

**Comment by berteh** [comment]
No dumb question, only a too obscure script :) Thanks  @UltraSalem for this clear walkthrough, I added it to the wiki, hope it's OK with you: https://github.com/berteh/ScribusGenerator/wiki#cards-deck-walkthrough

Glad you like the script
B.

**Comment by berteh** [comment]
but I found your other comment strange: "Also ensure you choose "single file" as an output option, otherwise it seems that only the last row of the CSV's pdf will get generated."

Actually this option should generate one sparate SLA (or pdf) for each CSV row. Didn't work for you ?
B.

**Comment by UltraSalem** [comment]
It might have been caught up in the next record issue at the time. When I first wrote my readme I was learning scribus and the script all in one day for my little project and didn't really know what I was doing. :) Happy for you to share my instructions, share and share alike!
