### ISSUE TITLE
Confusing naming of %VAR_NEXT-RECORD%

### ISSUE THREAD

**Issue by VynceMontgomery** [berteh/ScribusGenerator#118]
since NEXT-RECORD isn't really a variable to be populated, it should be named something else. My suggestions would be "%CONTROL_NEXT-RECORD%" or "%SG_NEXT-RECORD%"

**Comment by berteh** [comment]
good idea; will do 

(or feel free to push a change, if you do just  kindly make sure it supports both keywords for now, for retro-compatibility).

**Comment by berteh** [comment]
Done. 
Turned it to %SG_NEXT-RECORD%... but without retro compatibility, so you'll have to change your templates accordingly. Sorry: I didn't find a clean way to handle both notations without code duplicates.
