### ISSUE TITLE
Allow simple conditionals

### ISSUE THREAD

**Issue by VynceMontgomery** [berteh/ScribusGenerator#119]
it would be great if we could have simple conditionals. e.g., assuming I have a %VAR_balance%

%EXPR( balance > 0 ? "Black" : "Red" )%

Note: I am not trying to prescribe a syntax, merely suggest a functionality. Obviously, this can currently be done by adding a column to the CSV that contains the correct value, or by writing a preprocessor script that adds that column per the relevant logic. But it would be a convenient feature to build in for conditional formatting and even conditional inclusion of template parts.

**Comment by berteh** [comment]
Thanks Vynce for the suggestion.

I considered this some (long) time ago, and considered at that time that most of the scenarios I could think of could could be covered from the spreadsheet (including the computation of elements' position, colors, font sizes, dynamic text,...). It goes even further if you work with smart styles and color naming scheme.

I therefore didn't want to make the scribus "template" even less readable, and error prone (template languages are often ambiguous).  But I could reconsider if it is really needed.


I personally used to compute a single attribute in my spreadsheet, say "style", and then name my colors and styles accordingly in Scribus... and all colors named "background_warm" and "background_cold" and "background_%VAR_style%" can be black, or red, or different... or whatever you need.

**Comment by VynceMontgomery** [comment]
Yeah, I'm hoping, eventually, to avoid computing anything in the spreadsheet. I also want to do complete inclusion/exclusion of parts of the template based on whether they are used. For now, I often just have a VAR_hasFeatureX for each VAR_featureX. like, i have color TRUE (black) and color FALSE (white) and say like font color "%VAR_hasFaxNumber%"  and text "Fax: %VAR_faxNumber%"

**Comment by berteh** [comment]
I see your point.

I think I would create a non visible, non printed, non stacked layer, and set a dynamic attribute to all objects I want to hide, to "move" them to this hidden layer.  You could still do another layer if you want them hidden but "occupying" the space for layout reasons.

For instance to move a text frame to the hidden layer with id 1 (default Backround layer has ID 0), I'd add an attribute like:
Name: `LAYER`
Value: `%VAR_hidden%`
Parameter: `SGAttribute`
RelationshipTo: 

and putting in your spreadsheet value of `hidden` to `1` to hide, to `0` to show.


Duplicating an item (text frame or image frame,...) with such an attribute DOES duplicate the attribute as well... making the copy hide/show according to its own `hidden` value.

This solution has to me the advantage of being able to handle all visibility layout tests nicely from within scribus (hit F6 for layers dialog)... and benefit fully from its powerfull alignement / flowing /outline capabilities.

Let me know how this works for you.

**Comment by berteh** [comment]
for reference and for less advanced users here's the documentation on using SGAttributes for advanced template adaptations:

https://github.com/berteh/ScribusGenerator#more-advanced-uses

**Comment by berteh** [comment]
check it out if you like, just generate merged sla from these 2 files and compare pages 1 and 2 of the resulting document.

[visibility-dynamic.csv.txt](https://github.com/berteh/ScribusGenerator/files/2770818/visibility-dynamic.csv.txt)
[visibility-dynamic.sla.txt](https://github.com/berteh/ScribusGenerator/files/2770819/visibility-dynamic.sla.txt)

**Comment by VynceMontgomery** [comment]
I think that's a great idea, thanks!  I haven't used layers at all in Scribus, because none of my projects have required them, but from your description that sounds like it will work quite well. Thanks for taking the time!

It still leaves me doing calculations in my spreadsheet for hat to hide, but it's a much cleaner use of the existing SG capabilities.

**Comment by berteh** [comment]
I'll close this one for now, for the sake of keeping the template more or less readable.

Feel free to reopen if you experience other related problems that seem really unefficient to solve.
