### ISSUE TITLE
surprising behavior: stripping attributes?

### ISSUE THREAD

**Issue by VynceMontgomery** [berteh/ScribusGenerator#121]
`DefaultStyle` and `ITEXT` elements get their styling stripped if they are "empty" (meaning the CH attribute is empty). This is surprising, but probably rarely if ever significant to the actual document. However, it does make things difficult to debug. Also, attributes seem to be stripped when the value is set to %VAR_someVar%".  The reasons for this are less clear.

**Comment by VynceMontgomery** [comment]
I apologize; some of the attribute stripping is actually happening when i open and resave the document in Scribus, which I do to get the linebreaks back in so that my text editor can parse and syntax highlight the XML. That said, some of it does seem to happen in the SG layer, as well. Specifically, I think, Scribus removes the attributes when they are set to %VAR_foo% and VAR_foo is empty; SG appears to strip whole tags when the CH is empty, which Scribus then puts back but with no attributes. Still surprising, but now only 50% on SG.

**Comment by berteh** [comment]
I noticed the same "stripping" problem on Scribus behalf, leading to some applied styles being lost between the template and the generated document... but as only unused styles were lost as far as I noticed it was not too big an issue.

If it's an issue to you I could investigate further, but as this is on Scribus' side I'm not sure I'll be able to do  much.

SG cleans the empty variables by default, but you can change this behavior by setting ``CLEAN_UNUSED_EMPTY_VARS = 0`` on https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L54

**Comment by VynceMontgomery** [comment]
I think what I'm observing (`<ITEXT FCOLOR="%VAR_color%">` + `color = ''`=> SG => Scribus => `<ITEXT>` (with no FCOLOR at all) is actually entirely in scribus space and the surprising behavior was because I expect `FCOLOR=""` to act like None, which is not an option for FCOLOR (but is for PCOLOR and PCOLOR2).  So I now think this is not at all an SG issue, and am closing this ticket.
