### ISSUE TITLE
Please retain linebreaks between tags

### ISSUE THREAD

**Issue by VynceMontgomery** [berteh/ScribusGenerator#122]
The scribus output XML has linebreaks and indentation to make it easier to read; some step of the SG process removes the linebreaks between the tags. (I don't know python well, but presumably this is a matter of changing `result = result + line` to `result = "\n".join(result, line)` or something.)

**Comment by berteh** [comment]
good idea. will do. feel free to push code change if you'd like.

**Comment by VynceMontgomery** [comment]
My python is unlikely to be 100% PEP8 compliant, but I'll consider a few PRs if I can get the brainspace to turn on my coding brain.

**Comment by berteh** [comment]
fyi, fix is not that quick, as the output XML gets serialized in ElementTree module, which has no "pretty print" output.

I'm trying to find infos on availability of XML output modules shipped with Scribus, as LXML would do the trick nicely but is not shipped with all distributions.

**Comment by berteh** [comment]
fixed. I just hope that OSX ships the minidom library along python. If you can test it on mac that'd be great. thanks for the suggestion.

**Comment by berteh** [comment]
btw: indentation can be disabled by setting `INDENT_SLA = 0` in the backend config section.
