### ISSUE TITLE
Wording suggestion in README.md in Multiple Records on a Single Page section

### ISSUE THREAD

**Issue by rotor-head** [berteh/ScribusGenerator#129]
Just going back and reviewing the docs section for another small project and ran across this language in the README.md file:

> Simply drop the text %SG_NEXT-RECORD% in your document before each data entry but the first,
> 
The word _but_ here might be better changed out to _except_ and add the word _record_ to avoid any confusion for the reader.

Hence, it would read:
> Simply drop the text %SG_NEXT-RECORD% in your document before each data entry _except_ the first _record_,
> 

I knew what you meant given the most recent exchanges on the change in the naming convention and my questions regarding syntax case yet it still took me a second to re-read for the light bulb to go on. It is a small tweak but may help in readability and understanding for others.

**Comment by berteh** [comment]
done. good suggestion, thanks.

More are welcome, to made it both shorter and more understandable.
Should there be a next time don't hesitate to directly hit the "edit" button from the [README page](https://github.com/berteh/ScribusGenerator/blob/master/README.md). It will automatically create a copy for you to edit to your liking and send me for review.

thanks again.
