### ISSUE TITLE
Assigning attribute to rotation

### ISSUE THREAD

**Issue by iamgreenfire** [berteh/ScribusGenerator#130]
I recently discovered Scribus Generator and am thoroughly impressed and excited to use it. I did come across one thing that I couldn't seem to get to work, however, which is assigning an attribute to the rotation of an object to have the resulting image rotated based on which image is used. I have a column in my csv file for the image to use and another column for the number of degrees to rotate the object.

I found in the documentation that the correct name should be "ROT" I believe, and I have a column in my csv file that is the number of degrees that I want the object to be rotated, but when I run the script, all of the resulting files have the same rotation as the original file. I thought that I might be missing something in the RelationshipTo field, but couldn't find anything in the documentation to indicate what might need to go there...

I am pretty new to using this tool, so I may have missed something obvious, but if you have any suggestions for what I should try next, please let me know.

**Comment by berteh** [comment]
hello @iamgreenfire 
Indeed ROT should do the trick. 

Maybe you need to rotate slightly the image (just put any value but 0 in the rotation box, it will be replaced anyway), as ScribusGenerator does not create the attribute, but only looks to update its value.

The exact values to use on the attribute if you put it on a frame (image/text/render frame), provided your "degrees" csv column is called ``deg`` are:

| Name | Value | Parameter | RelationshipTo | Explanation 
| --- | --- | --- | --- | --- |
| ``ROT`` | ``%VAR_deg%`` | ``SGAttribute`` |   | rotation of the current object, in degrees, [0 , 359]

attached an example and data (just remove the .txt extensions)

[rotation350.sla.txt](https://github.com/berteh/ScribusGenerator/files/3020484/rotation350.sla.txt)
[rotation350.csv.txt](https://github.com/berteh/ScribusGenerator/files/3020483/rotation350.csv.txt)

Hope this works for you. 

FYI, to find it was indeed the ROT attributed I needed to change dynamically I just created a scribus document with picture, saved it, rotated the picture, saved under another name and did a "diff" comparison between the 2 files.

Let me know how this goes for you, and don't hesitate to share your tips and your creations in our wiki,to help others.

Berteh.
