### ISSUE TITLE
Dynamic images from line n are taken from line n+1

### ISSUE THREAD

**Issue by S1SYPHOS** [berteh/ScribusGenerator#131]
Hello there,
title says it all, I guess. When generating my document with `./sg/ScribusGeneratorCLI.py --single -c ./dist/data.csv -d ";" -o "." -n "result" example.sla`, everything is going well, except group 1 (= line 1 in csv, after header line ofc) gets the image of line 2, group 2 gets image of line 3 and so on .. very strange, and I can't figure out why ..

Any help really appreciated!

// Edit: In the csv, everything is in order, eg line 1 image is correct, line 2 image is correct, etc

**Comment by S1SYPHOS** [comment]
Ah well, one of them wasn't grouped, so I solved it myself - thank you very much for this great piece of software, wouldn't use Scribus at all if it wasn't for this :tada:

**Comment by berteh** [comment]
You're welcome, and congrats for finding the solution.

>
Don't hesitate to share your examples or tips on the GitHub wiki, to
help/inspire others.

Berteh.
