### ISSUE TITLE
Multiple input CSV files

### ISSUE THREAD

**Issue by S1SYPHOS** [berteh/ScribusGenerator#132]
Hey there,
among cover, introduction etc, my source document has two sections, one contains `%VAR_variable_category1%` fields, the other section contains `%VAR_variable_category2%` fields - you see where I'm going. Some of my CSV files contain headers like this: `variable_category1`, while others contain headers like this: `variable_category2`. 

Now, I'd like to insert multiple CSV files (with a wildcard, eg `-c some/path/*.csv`) to merge their respective matching headers into the document: would that possible to implement?

Thanks for your time & effort,
S1SYPHOS

**Comment by berteh** [comment]
hello Martin.
I don't quite get it, my bad. Let me try to rephrase what I think I understood:

You would like to use data from mutiple CSV, each having *only* different columns (variables), no common column (e.g. entry ID, for instance ``title``) needs to be matched between the files, all your CSV have exactly the same number of lines, and you would like to use variables from all these CSV files in a single Scribus (Generator) template.

If that's the case I'd recommend merging the CSV with a short script. You can customize the following to your liking, it uses the powerful [pandas](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html) Python library:

```
import pandas as pd

a = pd.read_csv("filea.csv")
b = pd.read_csv("fileb.csv")
merged = a.merge(b, on='title')
merged.to_csv("output.csv", index=False)
```

You can leave the ``on='title'`` out if you indeed don't need to match the entries between your different csv files... and you can accomodate more CSV file by putting multiple "merge" in sequence.

Kindly let me know if that works for you, and please share below your adapted script once you got it right... I'd be happy to add it to our ``utils`` script if it's flexible enough for others to reuse !

B.

**Comment by berteh** [comment]
If I did not understand your need at all kindly excuse me and please try to re-explain. An example is most welcome.

**Comment by S1SYPHOS** [comment]
I'm working with PHP mainly and already have a function for merging CSV files, but silly as I am, didn't think this - merging them would be a nice compromise! I'll go check that out! Also, I'd be glad to send a PR for adding a `composer.json` file, that way I can easily include it in PHP projects :+1:

**Comment by S1SYPHOS** [comment]
When using your suggested script, I'm getting this error: `pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 5, saw 15`.

But I went with your suggestion, using python to the rescue, and came up with this script to achieve what I wanted (in terms of merging CSV files):

```python
import pandas as pd
import glob

dfs = glob.glob('*.csv')
result = pd.concat([pd.read_csv(df, sep=';') for df in dfs], ignore_index=True)
result.to_csv('merge.csv')
```

**Comment by daybugging** [comment]
Having a composer file doesn't hurt anyone and enables PHP people to use this excellent package.

**Comment by S1SYPHOS** [comment]
I'll close this because I found a way to achieve what I wanted - thanks again!

**Comment by berteh** [comment]
glad you did. 
if you feel like sharing some of your results, or explain how you combine this with in php the wiki's all yours to inspire others !

**Comment by berteh** [comment]
and thanks @S1SYPHOS  for the merge script, I added it in the "utils" directory.

**Comment by daybugging** [comment]
I guess a new release would be in order 😎
