### ISSUE TITLE
ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by S1SYPHOS** [berteh/ScribusGenerator#138]
I seem to randomly (sometimes 10 files fail, sometimes 2, sometimes they are all processed as requested) get this nowadays, sometimes upon changing just a little bit in my `.sla` template files:

```text
    [176] => 01:51:59 - ScribusGenerator - INFO: ScribusGenerator initialized
    [177] => 01:51:59 - ScribusGenerator - INFO: Generating all files for dataList.sla in directory ./dist/2019_01/templates
    [178] => 01:51:59 - ScribusGenerator - INFO: parsing scribus source file ./src/2019_01/templates/dataList.sla
    [179] => 01:51:59 - ScribusGenerator - INFO: parsing data source file ./dist/2019_01/csv/Vorlesegeschichten.csv
    [180] => 01:51:59 - ScribusGenerator - INFO: source document consumes 3 data record(s) from 16.
    [181] => 01:52:00 - ScribusGenerator - ERROR:
    [182] => error: Traceback (most recent call last):
    [183] =>   File "./vendor/berteh/scribusgenerator/ScribusGeneratorCLI.py", line 159, in <module>
    [184] =>     generator.run()
    [185] =>   File "/home/fedora-user/Public/gendoc/vendor/berteh/scribusgenerator/ScribusGeneratorBackend.py", line 222, in run
    [186] =>     tmpElt = ET.fromstring(outContent).find('DOCUMENT')
    [187] =>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    [188] =>     parser.feed(text)
    [189] =>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    [190] =>     self._raiseerror(v)
    [191] =>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    [192] =>     raise err
    [193] => ParseError: not well-formed (invalid token): line 1, column 27268
```

It looks alot like #138, but
- my CSV worked before / still works randomly
- no XML-unfriendly characters

Help needed!

// Edit: When using one entry per page, it always works for all my template files, however, adding another and using `%SG_NEXT-RECORD%` etc, beforementioned problem arises ..

**Comment by berteh** [comment]
Would you by any chance be able to find you what word/tag/characters is in
your SLA at the position 27268 when it fails?

Even though the 'random' part of your statement bothers me bit more. Do you
see no pattern in the error occurrence?

Le mer. 24 avr. 2019 à 01:54, Martin Folkers <notifications@github.com> a
écrit :

**Comment by S1SYPHOS** [comment]
Well, that's fairly hard for me to debug, as it seems to be the temporary, compressed output of the destination file (which doesn't get written in the end). When minifying SLA files that worked, this position is seems to be the `%SG_NEXT-RECORD%` placeholder, though ..

Normally, I had text frame (tf) 1 on lvl 1, tf2 on lvl 2, and so on. At the end of the last text frame of each record (=> line of my CSV file), I put `SG_NEXT-RECORD` variable, except the last on the page.

When leaving it with the last record on the page, as shown below (the overflow inside the green `%VAR_Preis%` variable), more SLA's than before are produced, though not all of them:

![Screenshot from 2019-04-24 10-21-26](https://user-images.githubusercontent.com/12161504/56643879-d9585980-667a-11e9-8a65-b9a505ebc871.png)

**Comment by S1SYPHOS** [comment]
Alright, I narrowed it down to this:
There's a middle dot (`·`), which *by itself* doesn't seem to invoke the error. BUT, when there's a variable (see `%VAR_Altersempfehlung%` in the picture above) **behind** the middle dot, an error is thrown.

Now, I cannot comprehend fully why that's not always true: all CSV files use the same SLA template file (as shown above), which contains the sequence in question. Any ideas?

Thank you so far for being attentive, which makes working on open-source the great adventure it can (and should) be!

Cheers,
S1SYPHOS

**Comment by berteh** [comment]
You're welcome for the attention, thanks on your end for the feedback: it's always to see my work is useful to others too.

As for the error you mention I cannot reproduce it so far. 

Can you please try to find a way to see if the errors happens always with the same CSV entries (by changing their order slighlty and regenerating, for instance)... maybe that would help narrowing it down. Or if it always happens on a given position (each 12th CSV entry...), that would point to an memory issue in Python parsing.

Even though from the error message you reported it looks like the error happens before any data substitution is made, and should thus happen for each entry, solely based on the SLA content, indepently from CSV content.

**Comment by S1SYPHOS** [comment]
Hm, since I managed to solve this (sadly, by avoiding my beloved middle dot), this has become a low priority to me - it's a matter of finding the time to debug this thing, you know.

I'll leave this open as a reminder - in the meantime, if there are PANTONE® fans out there, I created [two scripts](https://github.com/fundevogel/we-love-pantone), generating master palettes for Scribus in XML format!

Cheers,
S1SYPHOS

**Comment by berteh** [comment]
nice script of yours, thanks. made a few suggestions in PR. would have loved to see it all python and not mixed language... as I had to install php just to try it out...  but that's just me ;)

If you are OK to share your sla+csv I can try to debug this middle dot thing.

thanks for the time spent one debugging SG anyway !

**Comment by S1SYPHOS** [comment]
Uninstall PHP, my friend, I rewrote everything to Python, officially being my first :snake: project!
Also, I added `.gpl` generation for GIMP / Inkscape, because it's fun :tada:

**Comment by berteh** [comment]
nice. congrats on your first script, and thanks for GPL generation. quite useful addition ;)

**Comment by berteh** [comment]
close since not able to reproduce. feel free to reopen if the issue arises again.

**Comment by S1SYPHOS** [comment]
Will do. However, the problem of "stacked" items after page 2 still persists. I'll post in a new issue ofc.

You rock!
