### ISSUE TITLE
support range for data

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#14]
add options to specify a range of data entries to use for generation, eg from 97 to 104, to ease template development testing. 
empty (in GUI) or missing (in CLI) would mean 1 and last, respectively.

**Comment by bjarnesvanberg** [comment]
I am currently working on this and have the core functionality working. I still need to work on the user input from both GUI and CLI.

**Comment by berteh** [comment]
wonderful, thanks!

**Comment by berteh** [comment]
don't hesitate to commit your dev version to another branch than master (even if not finished) if you want some help. 

About the GUI: don't hesitate to improve it drastically on the way if you want to & have the time, like having a visible separator or panel for more "advanced" settings [range, delimitor]  ;)

**Comment by bjarnesvanberg** [comment]
Roger that :) I will commit a feature branch and add the _help wanted_ label on the issue if I get stuck.

**Comment by bjarnesvanberg** [comment]
After clearing the confusion about different versions of Python I was able to create a functioning version of this feature in the CLI tool. It is still in a separate branch as there are no GUI integration yet. The branch can be found at this commit: 0e860e0951d86dd27de5de7ebf6db035c358a8ff 

(It will likely be a while before I have the time to work on this again... )

**Comment by berteh** [comment]
Thanks @bjarnesvanberg for this good work, looks clean from a quick look. I'll test it out and add a quick & dirty GUI integration in the next days.

**Comment by berteh** [comment]
integrated in master in commit 674eba5b08376 (support data range (#14), by @bjarnesvanberg  )
thanks again!
