### ISSUE TITLE
Feature: docker image

### ISSUE THREAD

**Issue by 4n70w4** [berteh/ScribusGenerator#140]
It would be very useful to have a docker image.

**Comment by S1SYPHOS** [comment]
Just to run the CLI command, correct?

**Comment by 4n70w4** [comment]
@S1SYPHOS yes. My Dockerfile:

```dockerfile
FROM python:2.7.16

COPY . /usr/src/myapp

WORKDIR /usr/src/myapp
```

Build:

`docker build -t scribus-generator:0.1 .`

Example:

`docker run -it --rm -v ./docs:/usr/src/myapp/docs -w /usr/src/myapp scribus-generator:0.1 python ScribusGeneratorCLI.py docs/tpl.sla -c docs/data.csv -n file_%VAR_id%`

**Comment by berteh** [comment]
thanks. added to the wiki: https://github.com/berteh/ScribusGenerator/wiki/Docker-image-for-ScribusGenerator
