### ISSUE TITLE
Please upgrade dependency to Python 3

### ISSUE THREAD

**Issue by luyatshimbalanga** [berteh/ScribusGenerator#141]
[Python 2.x will reach end of life in January 2020](https://pythonclock.org/). It will be nice to migrate the code to Python 3.

**Comment by berteh** [comment]
indeed. will try to do.

**Comment by JLuc** [comment]
Trunk version of Scribus is now compiled for python 3
(initial commit : http://scribus.net/websvn/listing.php?repname=Scribus&sc=1&rev=23278
ticket : https://bugs.scribus.net/view.php?id=15030 )

**Comment by luyatshimbalanga** [comment]
Python provide a script converting some python 2 codes to their python 3 version as accurate as possib;e. Simply use the command 
```
2to3 {python_script}
```
Where python_script is self-explanatory .

**Comment by berteh** [comment]
ported to python3 in branch https://github.com/berteh/ScribusGenerator/tree/python3
kindly test and let me know how this works for you.

I just don't want to make this the master, as the python embedded in my stock Scribus 1.5.5 (on ubuntu) is still python 2.7.

**Comment by MartinZaske** [comment]
I got this Scribus today:
https://sourceforge.net/projects/scribus/files/scribus-svn/1.5.6.svn/scribus-1.5.6.svn-snapshot-20200408-x64.exe/download

and I run yesterday's ScribusGenerator from the python3 branch just now and I gladly let you know that it works just fine. Well done. Thank you!

**Comment by berteh** [comment]
Thank you Martin for this good news.
