### ISSUE TITLE
Suggestion: SQLite, PostgreSQL and Base (Java databases) directly entries

### ISSUE THREAD

**Issue by EngDarkRoseAlchemist** [berteh/ScribusGenerator#142]
I'd like to merge directly from SQLite and PostgreSQL mainly. OpenOffice Base connection should good too.
Using ODBC drive can be a great update. :)

**Comment by berteh** [comment]
Kindly see issue #143 for more detailed answer.

Examples for different databases are in the SG wiki:
https://github.com/berteh/ScribusGenerator/wiki/Other-data-sources#export-from-a-standard-database

Please add more examples for Java databases or JBDC or OOo engines, to help
others.



The following could help you making the bridge:
http://digiassn.blogspot.com/2006/07/java-creating-jdbc-connection-to.html?m=1

I'd be happy to integrate some code that helps bridge with other databases
if you want to push some.

Have a nice day.
Berteh

**Comment by berteh** [comment]
I close the issue as the workaround seem satisfactory to me.

Feel free to re-open if you think it's important or you want to implement this yourself. 
Thanks.
