### ISSUE TITLE
question: Generate a new paragraph

### ISSUE THREAD

**Issue by joejoe2016** [berteh/ScribusGenerator#145]
Hi,
first of all thanks for all the good work.

I've got a question.If in scribus itself I go to Edit Text and in the big textbox I press enter then I generate a new paragraph. Is it also possible to define some special character or something so that ScribusGenerator triggers a new paragraph in the textbox?
I already use line breaks in my csv which results in a new line in the generated scribus file but the problem is that without the new paragraph the text in the last line is distributed over the whole line which looks quite strange although I select the correct allignment in the "edit text" window.
Any ideas?
Thanks
Joejoe2016

**Comment by berteh** [comment]
Hello @joejoe2016 

For now the substitution happening in https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L532 does replace ``\t`` (tab character in CSV) with ``<tab />`` in SLA and ``\n`` (newline character in CSV data) with ``<breakline />`` in SLA.

How would you suggest to distinguish a new paragraph in data from a simpler linebreak ?

If you feel like trying to update the code in this aera please feel free to give it a try and send me a pull request... maybe detecting two linebreaks (\n\n) in the CSV ?

**Comment by berteh** [comment]
closed for inactivity; feel free to reopen if you wanna push this further.
