### ISSUE TITLE
ScribusGenerator attempts to create log in /usr/share/scribus/scripts

### ISSUE THREAD

**Issue by garydale** [berteh/ScribusGenerator#15]
This location is normally not user-writable. While I can work around it by creating a log file and giving it world write access, a better solution would be to use the system's log facility or have it create the log in the user's home folder.

**Comment by berteh** [comment]
good catch. if you can feel free to propose a code update that fixes this, otherwise I'll put it on my todo list.

**Comment by garydale** [comment]
On 21/08/15 05:49 AM, Berteh wrote:
>
> good catch. if you can feel free to propose a code update that fixes 
> this, otherwise I'll put it on my todo list.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/15#issuecomment-133357207>.
>

Had another thought just now: have the generator append extra pages 
(possibly on an "as needed" basis) rather than creating separate files. 
When creating scribus output, this would allow tweaking the styles after 
the file has been generated, rather than re-running the generator.

My particular situation is that I'm producing a printed directory based 
on an xml file (converted to csv) containing contact information for 
various organizational units within the larger group. While the 
individual pdf output files are useful for sending to the units to check 
their own information, the final directory will have them usually two or 
three to a page. A single scribus file would make this easier - just 
drag the unit frames and delete empty pages.

**Comment by berteh** [comment]
that's issue #9, the one I'm currently working on, and it will be available in a few days ;)

**Comment by berteh** [comment]
fixed.
You can now easily change the logging settings in logging.config... like changing log file location, or adding a SysLogHandler (doc at https://docs.python.org/2/library/logging.handlers.html)
