### ISSUE TITLE
Error running command-line in Mac OS X: TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by hhallez** [berteh/ScribusGenerator#150]
Hi,

I have a problem using the CLI of ScribusGenerator.  I seem to be unable to run the scripts successfully.  Are there any suggestions, what I can do to get it working?  I don't get a logger file also, probably because the script does not get that far.
I use a Scribus in MacOS X Catalina 10.15.3.  I'm using Scribus 1.5.5. For python, I use the homebrew version.  
Here is my output:

 ```
Traceback (most recent call last):
  File "ScribusGeneratorCLI.py", line 124, in <module>
    generator = ScribusGenerator(dataObject)
  File "/Users/hans/PERSONAL/Oedelem/ScribusGenerator/ScribusGeneratorBackend.py", line 73, in __init__
    logging.config.fileConfig(os.path.join(
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 79, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 145, in _install_handlers
    h = klass(*args, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py", line 146, in __init__
    if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by berteh** [comment]
Thanks for the feedback.

Since the CLI version does not use Scribus at all the error could be somewhere with Python version.
It's working for me with python 2.7.17. What version are you using ?  find out by running `python --version` from the command line

**Comment by berteh** [comment]
I see you seem to be running python 3.8.1. Maybe convert the script to Python 3 and give it a go ?

running `2to3 -w *.py` could do, more info: https://docs.python.org/2/library/2to3.html

**Comment by hhallez** [comment]
I did use python2.7 in the end.  

I tried to do 2to3 but it didn't change ScribusGeneraterCLI.  I did change the other scripts.  
Running python ScribusGeneratorCLI still gave the error.  I'll try to have a look at it.

**Comment by berteh** [comment]
ported to python3 in branch https://github.com/berteh/ScribusGenerator/tree/python3
kindly test and let me know how this works for you.

I just don't want to make this the master, as the python embedded in my stock Scribus 1.5.5 is still python 2.7.

**Comment by jbm9** [comment]
FYI: I was reproducing this error with the current `master` HEAD, under python 3.10.6 on Ubuntu 22.04.  Checking out the `python3` branch seems to fix it.

Thanks for the generator; I use it to generate custom monthly diaries for myself.  It's a bit clunky to get everything together in the end, but I have old janky shell scripts to get the page order right for 2-up duplex printing and staple binding =)

**Comment by berteh** [comment]
python3 and MacOS are now included by default in master branch. plase update your script, test it out and don't hesitate to feedback !
