### ISSUE TITLE
impossible to have outfile name with the python3 version

### ISSUE THREAD

**Issue by naolivier17** [berteh/ScribusGenerator#152]
Hello. Before I used Scribus Generator (python 2.7 version) on Ubuntu 18 and no problems.
But now I use scribus Generator (python 3 version) on Ubuntu 20 and I can't choose the Output File Name. If I choose on letter or on number or one variable it the same massage error : 
`"ScribusGeneratorBackend.py",`` line 464, in createOutputFileName result= result.decode('utf_8' ) AttributeError : 'str' object has no attribute `'decode'.`
But if OutputFileName is empty, it's good. 
Thank

**Comment by naolivier17** [comment]
I use now the 1.5.5 scribus version and the ScribusGenerator script on mater branch (python 2.7) aund it 's OK. I don't know why but it's good for me.

**Comment by berteh** [comment]
(finally) looking into this.

for memory: to reproduce:

`python3 ScribusGeneratorCLI.py -n out%VAR_position%.sla example/Business_Card.sla`

**Comment by berteh** [comment]
should work now.
