### ISSUE TITLE
Scribus 1.5.5 crashing after launching scribus generator

### ISSUE THREAD

**Issue by flagadur** [berteh/ScribusGenerator#154]
Is this new version of Scribus working with this script??
EDIT : I'm using Ubuntu 20.04

**Comment by flagadur** [comment]
I'm a huge fan of your script, I'm using it everyday for my work, thanks a lot for your work on it ;) If it's not possible to make it work on the new version I will install an old version of Scribus.

**Comment by flagadur** [comment]
I'm using Ubuntu 20.04.

**Comment by berteh** [comment]
Hello. Glad you like ScribusGenerator.

Last time I checked out it worked ok with recent Scribus. You may need to use the version for python 3, as I think Scribus dev version is in the process of updating from python 2.7  to 3.x.

That version is available in a separate branch for now, as most people are still using Scribus stable, that ships python2.7:
https://github.com/berteh/ScribusGenerator/tree/python3?files=1

I've had one big report for this version stating that using output filename option is broken though, but hadn't the time to look into it yet. If you're familiar with python2 Vs python3 kindly have a look. Likely something to do with string encoding.

**Comment by berteh** [comment]
Side note: I'm always interested in examples of workflow or templates, if you feel like sharing some feedback please do!

(either here or in the wiki page)

**Comment by flagadur** [comment]
Thanks for your answer!
Actually, the problem was the standard version of Python for Ubuntu 20.04.
Installing old version of Python fixed the problem. I wasn't due to a new version of Scribus my apologies.

Side note : Actually I'm boardgame designer and all my prototypes are designed with this script. I have loads of files on my computer if you like. I shall see which ones I can share. What kind of examples would you need? The most complicated stuff I used were changing dynamically color and transparency of certain elements.

**Comment by berteh** [comment]
Thanks for the feedback.

All examples you're proud of are warmly welcome, doesn't need to be particularly complex, but it can too.
My aim there is more to give people ideas of possible real-life uses... and showcases other works.

**Comment by flagadur** [comment]
Hey! I did some cleaning and here are two examples of what I did with scribus Generator:
- Monsters is really simple but it's the kind of thing I'm doing most (placing images and text to create cards).
- Droids is more complex. I wrote a python script to generate a pseudo-random csv file and to launch Scribus Generator (README.txt to explain how to use it). Sorry for all the french comments I didn't think it would be shared... I can translate if you really want to share it. (I learnt python this way so it's reaaaally basic coding)

I put the file on wetransfer because it's quite Heavy (30Mo). I was wandering why my pdf are so heavy sometimes. I don't know where you would like to host it?

https://we.tl/t-eqnKLJcxDG

**Comment by berteh** [comment]
so sad I was too late to download your files. could you please send them again ? I'll try to monitor this more often in the next days.

**Comment by flagadur** [comment]
Here is a new link!

https://we.tl/t-i3olcvKoT3

**Comment by berteh** [comment]
Merci pour ces exemples ! j'ai vraiment apprécié ta manière de générer les CSV en partie aléatoirement, et le résultat est beau, bravo !
Dans quelle mesure puis-je les repartager (sur le wiki ou ailleurs) en guise d'illustration pour mon script ?

**Comment by berteh** [comment]
juste par curiosité:
une raison particulière pour ne pas avoir créé un template "droid" avec 2 pages (gauche-droite) qui reprennent les même éléments principaux ? une seule ligne dans le CSV pour chaque droide (R et V)... et surtout cela t'aurais évité de devoir autant jouer avec les transparences dynamiques (encore que je trouve cette solution élégante, merci ;)

**Comment by flagadur** [comment]
Aucun soucis pour le partager, après c'est un peu nul mes commentaires sont en français. 
C'est un projet qui n'a pas vu le jour, donc pas de soucis de confidentialité (et je suis le seul auteur sur le projet).
Ta question d'un CSV Unique est super pertinente, j'aurais clairement dû faire ça ! 
Par contre, je sais pourquoi je n'ai pas fait un template scribus unique. Si j'imprime les cartes deux par deux sur des A4, je n'en met que 6 par page et non 9 comme dans mon exemple. C'était par économie de papier ;) (oui oui je les imprime ensuite ^^).

**Comment by flagadur** [comment]
En format paysage j'aurais pu obtenir 8 par pages et non 9. (ça aurait été pertinent quand même dit comme ça)
