### ISSUE TITLE
Alt+Tab : mandatory

### ISSUE THREAD

**Issue by flagadur** [berteh/ScribusGenerator#155]
When you launch the script, at the end I have to : Alt+tab and close the windows manually.
(Because Scribus window rushed in the front of my screen).
Isn't there a option to close the window automatically at the end of the script?

**Comment by berteh** [comment]
Good idea.

Would you like to try to add this with a tick box option ?  It should all happen in the ScribusGenerator.py file.

**Comment by flagadur** [comment]
Sorry, but I really not feel like I can do it. I know only the basics for the python language and this seems a bit too complex for me.
What is a good idea for you? Would it be even possible to close the script and the window without automatically?

Did you see the examples I shared for you here: https://github.com/berteh/ScribusGenerator/issues/154

**Comment by berteh** [comment]
done. thanks again for the suggestion.
