### ISSUE TITLE
Page Break

### ISSUE THREAD

**Issue by Juan-UAH** [berteh/ScribusGenerator#158]
Hello,

I have found a problem with the script at the moment of creating the PDF.
I have a page in which I have put some records of a CSV, like the monsters card example.
Everything was fine. I used the merge in a simgle PDF options and was OK. Every page has a fixed number of records and the page looks really nice.
Then, I needed to change the page size (changing from a A4 format to a customized one). And that was the begining of the problems.
The first cards were OK, but at the end of every page I have the problem. I have half of a card in the bottom of a page and the other half in the next one. That does not occur if I not select  the merge in one PDF, only if I mark that option.
To recreate the (bug?) you could use the monsters card example and change the page size, increasing the high.
Are there any way to avoid it, for instance, adding a "page break" at the bottom of the page?

Thank you for your help and congrats for the awesome script.

**Comment by berteh** [comment]
Hello Juan-UAH.

I stumbled accross a similar issue some time ago, and noticed when you change the page size some other dimension is not changed... that is used by Scribus (and thus ScribusGenerator) to determine the theoretical size of new pages. You can change these dimensions via the menu Page > Manage page settings... just make sure they match your new page size and the ScribusGenerator should then work as expected.

B.

**Comment by berteh** [comment]
do yoy know if there is a way to include a page break in scribus ? I didn't find one. If there is in Scribus, then the generator could it, otherwise not.

**Comment by berteh** [comment]
I confirm I found no notion of page break in Scribus to implement something similar. You can always use the existing feature of the Scribus framebreak... but you need to make sure that the linked next frame is indeed on the next page.
