### ISSUE TITLE
Dynamic Images in Scribus 1.5.5 not working (Win 10 64 Bit)

### ISSUE THREAD

**Issue by zelyev** [berteh/ScribusGenerator#163]
ScribusGenerator's Dynamic Images are not working on 1.5.5 on Win 10 64 Bit. If I add %VAR_pic% in the filename field, the OK button simply stays grey. If I hit "Enter" it says: "%VAR_pic% The file could not be found..."

Dynamic Text works just fine.

Scribus 1.5.5
Ghostscript 9.53.3
Qt 5.9.7

**Comment by berteh** [comment]
Unfortunately after some update, the ok button only becomes available if an existing file is selected.

A possible workaround is to copy an image and renaming  %VAR_pic% ... and similarly for any other variable name you need to use for pictures. Just make sure to handle the file extension either in the file name, or in the CSV data, but not in both.

If you find another user-friendly way to input dynamic image path suggestions are welcome.

**Comment by zelyev** [comment]
Thank you very much berteh!

I named the image %VAR_PIC%.jpg. And in the PIC columns I named the files without the .jpg extension. It now works. I tried also the way round, and it worked as well.

It would be great if you could reach out to the Scribus developers for maybe finding a more convenient solution.

**Comment by UltraSalem** [comment]
I had same issue on Linux. My workaround was to choose one image, save the Scribus file, open the Scribus file in an XML editor, manually edit the image name text to the variable % format, then save and open back up in Scribus. Just using a temp image called  %VAR_PIC%.jpg is much more elegant!

**Comment by berteh** [comment]
I did update the README accordingly, kindly suggest improvements if you have a better wording: https://github.com/berteh/ScribusGenerator/blob/master/README.md#dynamic-images
