### ISSUE TITLE
Module Not Found Error, Windows 10

### ISSUE THREAD

**Issue by cummingsrob** [berteh/ScribusGenerator#165]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 24, in <module>
ModuleNotFoundError: No module named 'Tkinter'

I had this working about a year ago, but I'm struggling to get it working again. What am I missing?

**Comment by berteh** [comment]
Maybe you are running Python3 but with the Python version 2
ScribusGenerator.... or maybe your flavour of Python does not include the
TKinter GUI library?

For the first try downloading (or ''git checkout python3'') the python 3
branch.

For the second kindly run the Scribus internal script editor and check
python version and try running the Scribus Generator from there on,
checking for version and TKinter import. If that is not satisfactory play
check with the staff and forum of Scribus., Add I have no me Henk

Good luck!

B.

**Comment by cummingsrob** [comment]
I am running Python 3.8.7. It appears that it's 'tkinter' (lower case) not 'Tkinter' in this version.

**Comment by berteh** [comment]
Yes indeed, and the Python3 code for ScribusGenerator does indeed use that syntax:

```
import tkinter
from tkinter import Frame, LabelFrame, Label, Entry, Button, StringVar, OptionMenu, Checkbutton, IntVar, DISABLED, NORMAL, PhotoImage
import tkinter.messagebox
import tkinter.filedialog
```

Just make sure you download the python3 version, used for Scribus 1.5.x:
https://github.com/berteh/ScribusGenerator/archive/python3.zip
(or ''git checkout python3'' if you use the git repository)

and not the default Python2 version, that is used for Python2 shipped in (stable) Scribus 1.4. series... as there are a few other syntactic changes between these versions.

**Comment by berteh** [comment]
did it work for you by installing the  python3 version of Scribus Generator?
https://github.com/berteh/ScribusGenerator/archive/python3.zip

**Comment by cummingsrob** [comment]
I have not tried it yet. The client project I needed it for has been put on
hold.

Thanks for following up!


....................................................
    *rob cummings*
    *313 530 8002*

**Comment by berteh** [comment]
ok, you're welcome. Should be fine so I'll close the issue for now. Feel free to reopen or start a new one if you need help on this.

**Comment by cummingsrob** [comment]
The good news is that this version seems to be working. It no longer crashes and appears to work.

I do have an unrelated issue, though. I'm printing multiple records on a sheet, but I can't get record 1 to print. It always starts with record 2. It does not seem to matter where I put the %SG_NEXT-RECORD% tag. If I remove the next record from the first record, it prints the second record twice. Is there an order that the variables are read & replaced? Left to right? Top to bottom? Level by level?

**Comment by cummingsrob** [comment]
I removed the %SG_NEXT-RECORD% tag and it still starts with record 2.

**Comment by UltraSalem** [comment]
In my experience tags are read in level order, lowest to top. So I
design a single piece of my layout, put a new box with the
%SG_NEXT-RECORD% tag as the last thing in that layout, and then
duplicate the layout (including tag) multiple times to fill up the
document if I want multiple records per page. I then remove the tag
from the last copy of the layout on the page as the script already
knows that at the end of the page you go to the next record.

**Comment by berteh** [comment]
using this NEXT-RECORD feature really works, but  is so error prone I just compiled available info in a dedicated page:

https://github.com/berteh/ScribusGenerator/wiki/How-to-use-%25SG_NEXT-RECORD%25

please have a look, try see if it helps and improve its content of others to struggle less. Thanks !

@cummingsrob I could have a quick look at your template if you care to share SLA and (sample) CSV.

**Comment by cummingsrob** [comment]
The problem I'm seeing s that with 384 rows of data, it starts with record
2. When I reduce that to only 36 rows of data for testing, it starts with
row 1 like it should.

**Comment by cummingsrob** [comment]
Oops, you can ignore this for now. It somehow fixed itself. I think the
problem was either in LibreOffice calc or my CSV. ¯\_(ツ)_/¯

**Comment by berteh** [comment]
Congrats on finding your problem. Enjoy SG.
