### ISSUE TITLE
Bug? Simple PDF merge (not always!) crashes with StringIO.py line 271, in getvalue self.buf += ".join(self.buflist) MemoryError

### ISSUE THREAD

**Issue by abclution** [berteh/ScribusGenerator#169]
Yesterday got this error on a machine with 48 gigs of ram, moved the job to a machine with 16 gb of ram and the job completed.
Today both machines give the same error no matter what I try (including reboots...)

The merge data is only 6 separate lines of info, addresses and names, very simple.

Seems to happen when "Merge into single file" option is on.

![image](https://user-images.githubusercontent.com/10130237/106783485-07dad500-6654-11eb-9112-5c5115aab102.png)

Log attached below
[scribusGenerator.log](https://github.com/berteh/ScribusGenerator/files/5920268/scribusGenerator.log)

**Comment by berteh** [comment]
Sorry to read about your problems. As your template and data seems light I think it's not an issue relating to RAM... I've used this script for much more complex templates on very old laptops.

From the "memory error" info though it might be that Python cannot load the whole SLA to make it look good. Kindly try to remove this "prettyfication" step by changing

``INDENT_SLA = 1``   to
``INDENT_SLA = 0``

in ScribusGeneratorBackend.py, line 44

The generated SLA files will still be just as correct for Scribus to use... just no easy to read if you open them with a text editor.

**Comment by berteh** [comment]
now fixed by turning prettyfication OFF by default (it's not needed for Scribus anyway); kindly update your ScribusGenerator script and try again.

thanks for the issue report.
