### ISSUE TITLE
Scribus Generator error with new version

### ISSUE THREAD

**Issue by garydale** [berteh/ScribusGenerator#17]
The same .csv & .sla files that used to work with the previous version (just downloaded the new version today) is now generating an error "Could likely not replace a variable with its value, please check your Data File and Data Separator settings. moreover: invalid literal for int() with base10: '595.28'"

Now when I used to work, I mean that loosely. It would generate 78 output files when I expected 79. Moreover the first variable / field name didn't substitute on any of the files I looked at. I don't believe this is a fault of the .csv file because I loaded and re-saved it from LibreOffice Calc but got the same error. Also the file looks OK when I open it in a text editor.

I thought perhaps the script didn't properly recognize <lf>s as a line terminator. I tried opening the file in Wordpad and resaving it, which replaced the <lf>s with <cr><lf>s (verified by opening in Notepad) but still got the same error.

Any ideas?

**Comment by berteh** [comment]
Hello @garydale ,
That is certainly not acceptable! sorry for this, let's try to fix it!

Kindly tell me:
- do you use ScribusGenerator via Scribus Script menu (i.e. the GUI), or via the command line (the CLI)?
- what separators do you have in your data (what do you mean by "which replaced the s with s"), and
- what exact settings do you use (either screenshot for GUI or copy-paste of your command-line).

The error message you got ("invalid literal...") makes me think that maybe one field of your data (that contains '595.28' ) is expected to be an integer by Python, and not a number with a decimal part. Maybe the first data in this column has no part after the decimal separator?

If your data is not confidential could you send it to me?



The other matter of generating only 78 files when you expect 79 is even less acceptable. is it always the same one that is missing (like the 1st or the last?) or is it random? or could you find a likely "rule" that explains which one is missing?

**Comment by garydale** [comment]
On 11/09/15 10:58 AM, Berteh wrote:
>
> Hello @garydale <https://github.com/garydale> ,
> That is certainly not acceptable! sorry for this, let's try to fix it!
>
> Kindly tell me:
>
>   * do you use ScribusGenerator via Scribus Script menu (i.e. the
>     GUI), or via the command line (the CLI)?
>   * what separators do you have in your data (what do you mean by
>     "which replaced the s with s"), and
>   * what exact settings do you use (either screenshot for GUI or
>     copy-paste of your command-line).
>
> The error message you got ("invalid literal...") makes me think that 
> maybe one field of your data (that contains '595.28' ) is expected to 
> be an integer by Python, and not a number with a decimal part. Maybe 
> the first data in this column has no part after the decimal separator?
>
> If your data is not confidential could you send it to me?
>
> The other matter of generating only 78 files when you expect 79 is 
> even less acceptable. is it always the same one that is missing (like 
> the 1st or the last?) or is it random? or could you find a likely 
> "rule" that explains which one is missing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/17#issuecomment-139568358>.
>

I used it via Scribus Script.

The <lf> and <cr><lf> (line feeds and carriage-return line-feed) got 
stripped from the comment. Sorry. The .csv file uses all fields enclosed 
in quotes and separated by commas.

The settings don't appear to matter. What does matter is that it works 
when I generate individual files but not when I try to create a single 
file (of either type).

However it is now including the first field name in the output!

I'm not sure what file is missing but it's not the first or last. I 
created the individual files based on club number, which every club has, 
which should yield an odd number of clubs (79). However I only get 78 
output files.

According to KATE, the file has 81 lines, which is a line of column 
headings, 79 data lines and a final empty line. The data in the file 
isn't confidential, so I'm attaching the .csv file and the template I'm 
using. This should allow you to recreate the problem.

The other problem I'm having is that .csv doesn't allow me to include 
all the data I'd like. My original XML file has repeated fields and I 
can't find a .csv converter that will keep them. The .csv file I've 
included, for example, handle them as separate .csv files, which would 
mean I'm doing a lot of cut and pasting. Others take just the first 
instance of a repeated field, which is just as bad.

Don't suppose you could make it work with XML as well?

**Comment by bjarnesvanberg** [comment]
The page height and gap between pages are stored as floats but was earlier cast to int. This has been corrected.

@garydale you will have to test with your data again. To be honest I am not really sure what you are describing but please test to see if it has been fixed along with the cast exception fixed here.

**Comment by garydale** [comment]
On 11/09/15 04:18 PM, Bjarne Svanberg wrote:
>
> The page height and gap between pages are stored as floats but was 
> earlier cast to int. This has been corrected.
>
> @garydale <https://github.com/garydale> you will have to test with 
> your data again. To be honest I am not really sure what you are 
> describing but please test to see if it has been fixed along with the 
> cast exception fixed here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/17#issuecomment-139652942>.
>

Thanks. I can confirm that the new version did produce a 79 page file, 
one page per club, with my test data.

Unfortunately when I produce individual files, I'm still only getting 78 
with the missing one being neither the first nor last. This would 
suggest something is wrong with my data if the single-file output didn't 
produce the correct 79 pages. Since I sent Berteh the files, perhaps you 
two can figure it out?

Anyway, I'm going to try to rework my XML file to remove as many 
repeating fields as possible so that the conversion to .CSV gives me 
something I can work with.

Thanks for the script! Now that it's working, I can spend some time 
learning how to get the most out of it.

**Comment by bjarnesvanberg** [comment]
@garydale you'r welcome :)

With regards to the other problem you mentioned I think @berteh have a better understanding of both the problem and the data. Should we open a different issue for this?

**Comment by berteh** [comment]
@bjarnesvanberg thanks for spotting & fixing the float->int!

(I open a new issue for the other part of the message)

**Comment by berteh** [comment]
XML and repeating fields discussion is now at https://github.com/berteh/ScribusGenerator/issues/19

**Comment by berteh** [comment]
and the missing 79th file is discussed in #18

**Comment by bjarnesvanberg** [comment]
Nice! I am currently working on #14.

**Comment by garydale** [comment]
On 11/09/15 04:44 PM, Gary Dale wrote:
> On 11/09/15 04:18 PM, Bjarne Svanberg wrote:
>>
>> The page height and gap between pages are stored as floats but was 
>> earlier cast to int. This has been corrected.
>>
>> @garydale <https://github.com/garydale> you will have to test with 
>> your data again. To be honest I am not really sure what you are 
>> describing but please test to see if it has been fixed along with the 
>> cast exception fixed here.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/berteh/ScribusGenerator/issues/17#issuecomment-139652942>.
>>
>
> Thanks. I can confirm that the new version did produce a 79 page file, 
> one page per club, with my test data.
>
> Unfortunately when I produce individual files, I'm still only getting 
> 78 with the missing one being neither the first nor last. This would 
> suggest something is wrong with my data if the single-file output 
> didn't produce the correct 79 pages. Since I sent Berteh the files, 
> perhaps you two can figure it out?
>
> Anyway, I'm going to try to rework my XML file to remove as many 
> repeating fields as possible so that the conversion to .CSV gives me 
> something I can work with.
>
> Thanks for the script! Now that it's working, I can spend some time 
> learning how to get the most out of it.

I am having a problem with the new script generator again. I am flowing 
text through several text frames. When I create individual Scribus 
files, it works. However when I create a single output file, the 
subsequent page contain a group of frames with no text flow - I only see 
the first text frame's text.

Also, is it possible to have the script remove variables (and eol 
characters?) that match empty .csv fields? It's not a big issue but with 
the .csv file having to contain all possible fields, I have to do a lot 
of deleting to clean up the output file. Deleting variable names 
requires me to select the name then hit delete, while deleting an empty 
line just requires a delete. Having the script remove empty lines would 
be even batter.

**Comment by berteh** [comment]
@garydale  please create a new issue for each suggestion, it's easier for us to manage. removing variables and empty lines is now discussed in #21


About the flow problem I guess it's because the "merge" functionality does change some group ID, and maybe not in the right way... the lack of doc of the SLA format did not allow me to retro-engineer that part correctly I guess.

You could try commenting out (adding a # at the beginning) the following lines in ScribusGeneratorBackend.py, and see what results you then get. I expect that would restore the flow across frames, but generate a wrong sequence across all pages of the document... If that is indeed changing something to your problem, then at least I'll now where to look at with more precision:

    97      if version.startswith('1.4'):
    98           docElt.set('GROUPC', str(groupscount*dataC))
    
    211     if not (obj.get('NUMGROUP') is '0'):  
    212          obj.set('NUMGROUP', str(int(obj.get('NUMGROUP')) + groupscount))


If testing this is not easy for you kindly send me by mail (my github user name @gmail.com) your data and template, so I can try to figure it out.

**Comment by garydale** [comment]
On 13/09/15 04:09 PM, Berteh wrote:
>
> @garydale <https://github.com/garydale> please create a new issue for 
> each suggestion, it's easier for us to manage. removing variables and 
> empty lines is now discussed in #21 
> <https://github.com/berteh/ScribusGenerator/issues/21>
>
> About the flow problem I guess it's because the "merge" functionality 
> does change some group ID, and maybe not in the right way... the lack 
> of doc of the SLA format did not allow me to retro-engineer that part 
> correctly I guess.
>
> You could try commenting out (adding a # at the beginning) the 
> following lines in ScribusGeneratorBackend.py, and see what results 
> you then get. I expect that would restore the flow across frames, but 
> generate a wrong sequence across all pages of the document... If that 
> is indeed changing something to your problem, then at least I'll now 
> where to look at with more precision:
>
> |97      if version.startswith('1.4'):
> 98           docElt.set('GROUPC', str(groupscount*dataC))
>
> 211     if not (obj.get('NUMGROUP') is '0'):
> 212          obj.set('NUMGROUP', str(int(obj.get('NUMGROUP')) + groupscount))
> |
>
> If testing this is not easy for you kindly send me by mail (my github 
> user name @gmail.com) your data and template, so I can try to figure 
> it out.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/17#issuecomment-139913898>.
>
I commented out line 210 as well, to get past an error message about 
indentation. That let the script proceed to completion. The text frames 
were ungrouped this time but they also continued to be unlinked.

**Comment by berteh** [comment]
ok, thanks for the confirmation. I'll have a look at it, and report in #22 .

**Comment by garydale** [comment]
On 13/09/15 05:42 PM, Berteh wrote:
>
> ok, thanks for the confirmation. I'll have a look at it, and report in 
> #22 <https://github.com/berteh/ScribusGenerator/issues/22> .
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/17#issuecomment-139921238>.
>
Thanks Berteh. Even as is, the script could save me a ton of work.

**Comment by berteh** [comment]
should be fixed now. thanks for the feedback.
