### ISSUE TITLE
python3: system specific file encodings produce incorrect SLA files (Windows and non-UTF-8 systems)

### ISSUE THREAD

**Issue by SunStrom** [berteh/ScribusGenerator#171]
Hi,

I just tried the python3 port of this great script on Windows. Unfortunately, it didn't work quite as well as the older version.
I found the following issues:

A)
The CSV file format changed. Python2 versions accepted (only?) utf-8 encoded CSV, which I produce with LibreOffice. 
The python3 version expects "system-native" encoding, i.e. Win-1252 on my Windows box. Cause is the open() call used, which was "default UTF-8" in python2 and is "default system-native" in python3.

Symptoms are for example that filenames generated from variables with umlauts (äöüß) are generated incorrectly.

B)
The SLA files are opened (written) with default encoding too. This causes parsing errors in scribus later on, because variables are automagically converted from UTF-8 to system-encoding when writing the file.

As a stop-gap measure I added `, encoding="utf-8"` to every "open" call in "ScribusGeneratorBackend.py" which fixes the problem and reverts to the old "utf-8 only" behaviour.

**Comment by berteh** [comment]
thanks for the report.

Is this workaround you propose (forcing utf8) acceptable to you ? Would you like to submit a pull request with your code changes to share them with other users ? I'd be happy to merge it.

**Comment by SunStrom** [comment]
Forcing utf8 was OK for me, because IIRC it mirrors the old behaviour on Windows. On *nix it probably would not matter either, because most are utf8 anyways. The only reason I consider this a hack is because a) it might break other things (but I don't have any examples) and b) I do not consider it nice behaviour because it is undocumented.

As for the pull request: I don't have a devel setup - I even registered this github account just to report this.
I'll try to set something up but can't promise ATM.

**Comment by SunStrom** [comment]
Okay, that was stupid:
1.) I just found the documentation clearly stating that UTF-8 is needed, so please disregard my previous comment.
2.) I tried to create a pull request with my brand new github account ;-)

**Comment by berteh** [comment]
congrats on the github account; and thanks for the PR !
