### ISSUE TITLE
Tkinter not found

### ISSUE THREAD

**Issue by bigbore** [berteh/ScribusGenerator#178]
I installed Scribus 1.5.6.1 in a Windows7 x64 VM to test it and found that ScribusGenerator will not start. Works in 1.5.5.

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 24, in <module>
ModuleNotFoundError: No module named 'Tkinter'

**Comment by berteh** [comment]
Scribus 1561 ships with python version 3, you need another version of the Scribus Generator. 

Please see the download link in the install documentation.

You can have the 2 versions at the same time on your computer if you want to keep working with older Scribus 155 at the same time, just extract their archives to different directories.

**Comment by bigbore** [comment]
OK, works now. Thanks for the quick response
