### ISSUE TITLE
How to print from commandline?

### ISSUE THREAD

**Issue by supersexy** [berteh/ScribusGenerator#180]
How to automate printing?

**Comment by berteh** [comment]
Hello.
You should look at your OS-specific command line printing tools. 

For linux that would be `lpr` or `lp`, which can take PDF as input for most modern (non RAW) CUPS drivers: https://www.networkworld.com/article/3373502/printing-from-the-linux-command-line.html

For windows that would be `print` or `lpr`: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/print-command-reference

Don't know for mac.

You need to 

1. generate the SLA using ScribusGenerator CLI: https://github.com/berteh/ScribusGenerator/wiki/Running-Scribus-Generator-from-the-command-line#running-scribus-generator-from-the-command-line - https://github.com/berteh/ScribusGenerator/blob/master/README.md#running-scribus-generator-from-the-command-line
2. turn these SLAs into PDFs : https://github.com/berteh/ScribusGenerator/wiki/Running-Scribus-Generator-from-the-command-line#generate-pdf-from-command-line
3. print these pdf (see above)

**Comment by berteh** [comment]
if you create a small script to integrate these steps kindly share it here or in the wiki; I could interest others !

**Comment by supersexy** [comment]
Right you are, keep the printing part apart completely makes sense, thanks for the hint! I will share!

**Comment by c-nascimento** [comment]
Is it possible send a TXT file to "Microsoft print to PDF" by command line?

**Comment by berteh** [comment]
@c-nascimento 
Probably. 
In linux that'd be ``pandoc input.txt -o output.pdf``.  

Look online for a windows equivalent: https://duckduckgo.com/?q=command+line+print+txt+to+pdf+windows  ... and kindly don't squat an existing support discussion but create your own in a more appropriate location.
