### ISSUE TITLE
Scribus Generator not working

### ISSUE THREAD

**Issue by perlwonk** [berteh/ScribusGenerator#191]
I'm running Scribus 1.1.5 on Ubuntu 20.04.  I downloaded the three scripts (ScribusGenerator.py, ScribusGeneratorCLI.py and ScribusGeneratorBackend), put all in the same folder and from there ran ./ScribusGeneratorCLI.py test.sla , where test.sla was just a simple test file and got this output:

Traceback (most recent call last):
  File "./ScribusGeneratorCLI.py", line 124, in <module>
    generator = ScribusGenerator(dataObject)
  File "/home/chuck/Combarriers/Documents/test/ScribusGeneratorBackend.py", line 62, in __init__
    logging.config.fileConfig(os.path.join(
  File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by berteh** [comment]
Hello @perlwonk 
Please delete those 3 script files and follow the install instructions at https://github.com/berteh/ScribusGenerator#how-to-install-scribus-generator-

You actually need a few more files, all provided in the zip package.

Then try opening and running the "business card.sla" from the example directory, for instance.

Have fun, and don't hesitate to come back if you have problems, and to share you examples.

**Comment by berteh** [comment]
and Scribus 1.1.5 is _ancient_, unless it's a typo ;9

You can find a more recent scribus-ng (1.5.6 for your distro) at https://launchpad.net/~scribus/+archive/ubuntu/ppa

**Comment by berteh** [comment]
no answer... I guess an update of Scribus and ScribusGenerator did solve your issue.
