### ISSUE TITLE
Can't substitute VAR name for image

### ISSUE THREAD

**Issue by w9ran** [berteh/ScribusGenerator#193]
I'm using Scribus version 1.5.7 and am having difficulty associating a variable name with an image field.   I've created the image field in Scribus using one of my images as an example just as you show at 8:00 in your tutorial.   But when I try to change the name of the test image by typing %VAR_image% (for example) into the file name box as you show at 8:15 - Scribus refuses to accept my entry with the message: 
%VAR_image%  
File Not Found 
Please verify the correct file was given.

This is driving me nuts ;-)   Especially since after failing a dozen times I happened to try it again and it worked, and that field now shows the image with the letters DUMMY superimposed, which I assume is to show it is a placeholder.   I did the same thing that had failed previously and suddenly it worked - but I couldn't get it to work for any other image fields consistently.  Finally I tried creating an empty text document with the %VAR name and that works one time then next time the image fields disappear again.  The text fields are fine, it just won't accept the images.   And while possibly unrelated, Scribus 1.5.7 seems to crash a lot.

I would certainly appreciate any help with this vexing problem!
Thanks, Bob

**Comment by berteh** [comment]
Hello Bob.

One quick workaround may be to duplicate any of your picture and rename the copy %VAR_image%... and similarly with any other variable you need in pictures name.

This problem is due to more recent Scribus checking for files existing in the file selection diagram... whereas it did not at the time I recorded the tutorial.

I hope this works for you, and if you have an idea for a more user-friendly way to include dynamic pictures in Scribus suggestions are welcome.

**Comment by w9ran** [comment]
Thanks very much for the quick reply and suggestion.  It makes sense and I can choose those VAR files for my images (must select "All Files" and remove the .jpg extension).    But when I run the script only the text and graphic fields appear.  There is just blank space where the images should be. 

I ran into this problem a couple of months ago and reverted to verions 1.4.8 of Scribus to get around it.   Unfortunately I must have opened the .sla in the newer version by mistake because now I can't open my .sla file in 1.4.8,  even after editing the version in the xml file.   So I seem to be stuck with 1.5.7 which aside from being buggy, doesn't seem to be compatible with Scribus Generator - can you confirm that it is?

If we can't get this to work I will have to go back and re-create the document from scratch evidently, unless I can figure out how to overcome the version check.   It seems really dumb to make a tool that is not file compatible.   I know that my variable names match the columns in the csv file because it used to run under 1.4.8 and I would gladly go back if I could just get the .sla to open properly.

**Comment by w9ran** [comment]
To clarify:  I'm not referring to Scribus Generator when I said "dumb".   I mean Scribus itself.   For example, I copied the .sla file made by 1.5.7 and edited it in Notepad++ to change the version from 1.5.7 to 1.4.8.    But when I try to load it into version 1.4.8 the result is a crash.      At the very least, it should provide an error message  and allow the user to choose what to do.  Crashing when opening an xml file is just an indication of bad code!

**Comment by w9ran** [comment]
I was lucky to find an old backup copy of my .sla file from December that was compatible with version 1.4.8.    The document looks fine but now when I try to run the Scribus Generator script I get the following error, which appears to be a problem in ScribusGeneratorBackend.py  (pasted below).  If you can help me resolve this problem I will be able to run my job in 1.4.8 and we can forget about the other problem for now.   Thanks very much!
Bob
---------------------
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Users\ranic\Downloads\ScribusGenerator-python3\ScribusGenerator-python3\ScribusGenerator.py", line 26, in <module>
    import ScribusGeneratorBackend
  File "C:\Users\ranic\Downloads\ScribusGenerator-python3\ScribusGenerator-python3\ScribusGeneratorBackend.py", line 277
    def load_json(self, json_file: str) -> list:
                                 ^
SyntaxError: invalid syntax

**Comment by berteh** [comment]
There are 2 different versions of ScribusGenerator (SG), check out the installation instructions. One for old Scribus, and one for Scribus 1.5.6+ (updated to Python3 engine, which has a more modern syntax).

You can have both at the same time on your machine, just keep them in separate directories.

SG should work just fine in 1.5.7, many people confirmed it, but I can't say personally as I'm still using 1.5.6.

Images not showing in the generated document is usually just a matter of relative directories: Scribus does store images paths with a relative address. So if you save your generated document in a parent or child folder it cannot find the images at the appropriate place.

Try moving your generated file (SLA) in the same directory where the original SLA was, and opening it in Scribus from there... or open the generated SLA in a text editor to check the path of the image.

I recommend using a more recent version of Scribus, since it has really improved performances in the 1.5.6 branch... but as the files are not retro-compatible that's obviously your choice.

Hope this helps.
B.

**Comment by berteh** [comment]
For the images, you could also rename that image %VAR_image%.jpg to avoid the extra step of needing to pick 'all files'. But then you need to remove the jpg extension from your data table.

**Comment by w9ran** [comment]
Again, many thanks.   I had forgotten there were two versions!   After downloading the original script for older Scribus I have 1.4.8 working and I think I'll be able to get 1.5.7 working too, since I inadvertently created the same problem in each.  That is, I specified a subdirectory for SG to place the generated files in, and as you say, it cannot find the images there.     As soon as I specified the main directory the files were created properly with images.    I can move the files manually, no problem.

I have been improving my Scribus skills and now am confident I'll be able to put SG to even more use.  Thank you for this excellent tool and for your help and support.
Bob

**Comment by berteh** [comment]
You're welcome.

I like to generate my output files in other locations too, keeping things organised. I therefore make symbolic links to the images folders in the output directory, matching the relative structure of the source template. Works fine.

Hope this helps.

**Comment by drentsoft** [comment]
> Hello Bob.
> 
> One quick workaround may be to duplicate any of your picture and rename the copy %VAR_image%... and similarly with any other variable you need in pictures name.
> 
> This problem is due to more recent Scribus checking for files existing in the file selection diagram... whereas it did not at the time I recorded the tutorial.
> 
> I hope this works for you, and if you have an idea for a more user-friendly way to include dynamic pictures in Scribus suggestions are welcome.

Hi I'm also coming up against this issue (in Scribus 1.5.8) but I'm not sure I understand your work around. Are you saying to rename the image frame to **%VAR_image%**?
Or are you saying to rename the file to be linked?

For now I think I can just search for the image link in a text editor and change it to use %VAR_image% manually but would be great to understand how to do this in Scribus itself.

Thanks,

Derwent

**Comment by berteh** [comment]
Hello Derwent.

None of your suggestions. I propose to have *another* (extra) file named after your variables in the directory of your images, so you can pick that file from the Scribus file selection dialog.

For instance to use 2 dynamic images (a thumbnail and a poster) in separate frames from a single variable 'movie' in the data, I would 
- create 2 extra images (or duplicate one thumb and one full) and 
- name them 'thumb_%VAR_movie%.jpg' and 'poster_%VAR_movie%.jpg'
- pick these 2 new images in my SG template. they will show up nicely during the design... and still be replaced dynamically when generating the full document(s).



Fyi The name of the frame is not used by SG, but if you use a variable name therein it will be replaced just like anywhere else.

This scheme can be adapted to work with dynamic subfolders for images too, eg if you want to keep the thumbnails and posters into separate folders.

Hope this helps. Let me know if not, I'd try to do a quick screencast.

**Comment by drentsoft** [comment]
Ah I think I understand! Thanks!

`#CSV
movie, year, rating,
jaws, 1975, 8.5`

`#Folder: thumb_%VAR_movie%.jpg, thumb_jaws.jpg`
the first file in the folder gets around the non-existent issue in Scribus, allowing you to "get" the file, SG then replaces thumb_%VAR_movie% with thumb_jaws based on the name in the CSV.

**Comment by berteh** [comment]
Yes, and you're welcome.

**Comment by imba-pericia** [comment]
Scribus 1.6.2
I don't know if it's easier or not, this version doesn't allow you to add a non-existent image, I got out of the situation like this:
- renamed an arbitrary image to a variable name without extension
- imported it
- deleted the image file in the directory
- reopened the layout file
![image](https://github.com/user-attachments/assets/5edafd01-4046-4505-92f2-29579c360fed)

Then everything follows the instructions.
