### ISSUE TITLE
Convert pdf to sla format

### ISSUE THREAD

**Issue by etho201** [berteh/ScribusGenerator#198]
Is it possible to use ScribusGenerator (preferably the CLI) to convert a single `.pdf` file into a Scribus `.sla` file? Also, can this be achieved without a `.csv` file?

**Comment by berteh** [comment]
No, it's not.

As far as I know you can open a pdf in Scribus and then save as a SLA. Some PDF elements may get lost (interactive forms or other), not for basic text, shapes and pictures it works.

**Comment by etho201** [comment]
Yes, opening in Scribus and saving as `.sla` works well, but I was hoping to be able to accomplish this from the command line.

Basically, I'm looking for the opposite of this:

```bash
scribus -g -py to-pdf.py file.sla
```

**Comment by berteh** [comment]
Maybe try to code it yourself by adapting https://github.com/aoloe/scribus-script-repository/blob/master/sla-import/sla-import.py

... or ask @aoloe if he can do it for you, he's both knowledgeable in Scribus and very friendly :-)

**Comment by etho201** [comment]
I pretty much have this working, using the following:

Create a file named `to-sla.py` with the following contents:
```python
import os, scribus

if scribus.haveDoc() :
    filename = os.path.splitext(scribus.getDocName())[0]
    scribus.saveDocAs(filename+".sla")
else :
    print("No file open")
```

Now run:

```bash
scribus -g -py to-sla.py file.pdf
```

This will open Scribus and will save the file as an `.sla` file, but the only gotcha is the `PDF-Import` window appears first and you have to hit "enter" to select to import `All pages`. This may be a good thing if for some reason I wanted to change the number of pages I want to import; however, I'd like to make this completely non-interactive. At the end of the day, a single press of the `enter` key isn't so bad. ;)
