### ISSUE TITLE
Using XPOS, YPOS WIDTH and HEIGHT attributes

### ISSUE THREAD

**Issue by thibaud** [berteh/ScribusGenerator#199]
FHi,
thanks for this great script!
I am working on a book cover project to replace my old covers.
It works like a charm when I replace only the fields by variables (title, abstract...), but it fails when using the X_POS, Y_POS, WIDTH and HEIGHT Scribus variables for defining the position or the size of objects.
In fact the values are well recorded as attribute, but in the final document, when XPOS attribute is correct, the "real" XPOS has a wrong value. 
It seems that the values are correctly replaced, but the final values are incorrect. For example, for the red back cover object, named "QUATRIEME" in the .sla document, I'm asking the value with %VAR_QUATR_XPOS%. And the value in my CSV sheet is 20,05 (my document use cm as a unit).
However, the final XPOS attribute for this object in the generated document is -3,5278. I do have not this value in my CSV (only one is <0).
<img src="https://i.imgur.com/n8vpgGr.png"/>
Here is how I fill the attribute dialog box:
<img src="https://i.imgur.com/w7EwIgY.png"/>

Here is how I fill the ScribusGenerator main dialog:
![image](https://i.imgur.com/TmJgzNr.png)

Here is a complete minimal working example: https://thibaudhulin.net/MWE/scribusMWE.zip
In the mwe.csv example, a lot of values are useless for the generator to ignore, but you can see then at the last rows.
And here is all the value from the .sla document:
`                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_P24_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />

                <ItemAttribute Name="HEIGHT" Type="none" Value="%VAR_P24_HEIGHT%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_P24_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_PREM_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TR_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="HEIGHT" Type="none" Value="%VAR_TR_HEIGHT%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT10_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_QUATR_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_IMG14_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="YPOS" Type="none" Value="%VAR_IMG14_YPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT15_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT16_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT17_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT18_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="XPOS" Type="none" Value="%VAR_TXT22_XPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />
                <ItemAttribute Name="YPOS" Type="none" Value="%VAR_TXT22_YPOS%" Parameter="SGAttribute" Relationship="none" RelationshipTo="" AutoAddTo="none" />`

Best,
Thibaud.

**Comment by berteh** [comment]
Hi Thibaud.

Scribus seems to store these (position/size-related) attributes in an internal unit (maybe pt?) that gets converted per the users display preference in the UI only, depending on the print area of the current page and the position of this page in the UI (i.e. single or dual page view).

So I had to position a few elements in one A4 page (or other format you use) and look at the value saved in SLA to map (roughly):
x 12cm ~ XPOS 440.157480314961
y 9cm ~ YPOS 275
w 6cm ~ WIDTH 170.07874015748
and so on... but the script does work. 

I couldn't download your files to have a look (link KO), but check out the attached to try it for yourself (extract and generate in the 'examples' directory to have a working image link)
![image](https://user-images.githubusercontent.com/36950/160260267-51d416ec-4553-4c0a-9736-217cec7476d4.png)
[pos-size-attributes.zip.txt](https://github.com/berteh/ScribusGenerator/files/8356511/pos-size-attributes.zip.txt)

**Comment by berteh** [comment]
-et changer les unités du document en 'pt' n'est pas beaucoup plus utile parce que Scribus soustrait visiblement les 'bleeds' et autres marges de la taille de page... en déduire la position souhaitée reste donc imprécis.

Mais si vous trouvez une formule pour les calculer je suis preneur pour l'ajouter dans la documentation ;-)

**Comment by thibaud** [comment]
Hi @berteh ,
many thanks for your answer!
Sorry, water under the bridge ! Health difficulties last year, but altough the summer is coming, I come back to this interesting work.
For my mwe, here is the good link: https://thibaudhulin.net/MWE/scribusMWE.zip
I tested your example, but it occurs something strange: the picture is not always ate the same place during the repetition.
Here what I get:
![Capture d’écran du 2023-07-07 13-36-09](https://github.com/berteh/ScribusGenerator/assets/88024/bdc28e35-2ed2-4eb6-9d4b-6223f841de30)
To convert units to cm, I multiply the unit by 1/(2.54*72). In fact, the amount of information making up a one-inch line is 2.54 cm, and 72 is the resolution in ppi.
I have a lot of elements per cover: author's title, but also images, cover text, and so on.
Here's an image of the template to help you understand: 
![image](https://github.com/berteh/ScribusGenerator/assets/88024/c55c55cd-ddf4-4f7a-a61b-17fe28ac2a1d)
Unfortunately, this is the result I get with the generator: 
![image](https://github.com/berteh/ScribusGenerator/assets/88024/05db3186-0e22-4adc-84d9-ec97b7a537b2)

**Comment by thibaud** [comment]
Hum, changin the values, the picture of the author is moving... so, I think that's also a problem of values...

**Comment by thibaud** [comment]
Bonjour @berteh ,
comme ce MWE peut vous sembler un peu complexe avec beaucoup de champs, j'ai tâché d'expliquer autrement ce problème qui est de convertir des positions et des tailles données en millimètres vers des "unités Scribus".
J'ai posté un exemple très simple ici : comment déplacer un carré dans un cercle ?
 https://forums.scribus.net/index.php/topic,4647.0.html

**Comment by thibaud** [comment]
The edition of the path and copath attributes is possible with ScribusGenerator, and it works: it is necessary in order to resize a polygon. To convert a centimeter to units, you can use the formulate =2,54/72.
You can have a look to PAGEXPOS and PAGEYPOS attributes from your .sla file because Scribus don't use always the left high corner to position elements.
This script is very useful! Although it will take a lot of time to fix my books'cover with this method... :roll_eyes: 
Great script, I hope you will be able to update it! Merci beaucoup !
Problem solved! :+1:  :smile:

**Comment by thibaud** [comment]
The edition of the path and copath attributes is possible with ScribusGenerator, and it works: it is necessary in order to resize a polygon. To convert a centimeter to units, you can use the formulate =2,54/72.
You can have a look to PAGEXPOS and PAGEYPOS attributes from your .sla file because Scribus don't use always the left high corner to position elements.
This script is very useful! Although it will take a lot of time to fix my books'cover with this method... :roll_eyes: 
Great script, I hope you will be able to update it! Merci beaucoup !
Problem solved! :+1:  :smile:
