### ISSUE TITLE
Errors with CLI on Windows

### ISSUE THREAD

**Issue by bjarnesvanberg** [berteh/ScribusGenerator#20]
I have tried to run the ScribusGeneratorCLI.py from a normal windows command prompt which resulted in this error:
```
C:\Users\Bjarne\Programming\ScribusGenerator>python ScribusGeneratorCLI.py
  File "ScribusGeneratorCLI.py", line 86
    print ''.join(msg)
            ^
SyntaxError: invalid syntax
```
After fixing this and a few other bugs I committed the changes to branch clifix (5b42327ec6c0c7c79d8aa39a36d918815a372906)

I am not sure if I see these errors because I am on windows or because of the Python version (3.4.3) I am using or something like that. Anyway I have left the changes in the clifix branch. It would be nice if someone else could test this on windows before merging into the master branch.

**Comment by bjarnesvanberg** [comment]
Ok I think this and many other errors I get is related to the way Python 2.x and Python 3.x is handling bytes from a file. I guess I just have to install a version 2.x... another day.

**Comment by bjarnesvanberg** [comment]
I forgot to leave a link to where I found my hint:
http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface

**Comment by bjarnesvanberg** [comment]
This is just me running Python 3.x. I installed Python 2.7 and everything worked fine. If we want to support Python 3.x in the future we might have to work on how we read and parse data from files. 

For now I don't see this as a relevant bug so I will close it.

**Comment by berteh** [comment]
ok. thanks for the note. as python 2 is still the default on many OS I'd still stick to that for a while... but do you have another opinion?

**Comment by bjarnesvanberg** [comment]
No, not at all. I just happened to install the highest version number when downloaded it.
