### ISSUE TITLE
Invalid --firstrow and --lastrow options

### ISSUE THREAD

**Issue by hynekcer** [berteh/ScribusGenerator#202]
It is not possible to restrict the output to the first N lines.

Example `ScribusGeneratorCLI.py --lastrow 10 ...`

The output contains the lines from 2 to 10. The first row is removed.

The same problem is with ScribusGenerator.py and also is in the branch for Python 2.

This is because text lines are usually counted from 1, but indexes in Python start from zero. (PR submitted)

**Comment by berteh** [comment]
thanks for the fix.

I don't see the same problem for the python2 branch (master) though, since the row[0] is the CSV head in that case, meaning the needed -1 index shift is handled from not generating any entry for row 0. The CSV parsing mechanism has been updated in python3 branch.

**Comment by hynekcer** [comment]
Then I understand how this bug was possible. Tthe same code was well tested originally for python2, but such dependency on refactoring was not expected. Thanks
