### ISSUE TITLE
ScribusGenerator not using To Frame Size in image frame settings

### ISSUE THREAD

**Issue by drentsoft** [berteh/ScribusGenerator#205]
Hi,

I'm using ScribusGenerator 3 for Scribus 1.5.8 (64 bit) on WIndows 10 Pro and Windows 11 Home. 
I'm trying to generate files from a CSV but a lot of the images that are being imported don't look like they've been applied. however if I go into the image frames' Contents Properties and toggle Proportional or To Frame Size (both selected in the original template file) then they suddenly appear, scaling correctly into place. Is there a workaround for this?

Part of the log file, the part where it actually generates one of the files. Please let me know if you need more, it's very long and the file paths are also long.

```
2022-11-09 17:37:58 - DEBUG - create_output_file:729 - computing output file name from menu_%VAR_card_variant%-generated (count is 16)
2022-11-09 17:37:58 - DEBUG - substitute_data:546 - Replacements updated: ['P', 'A', 'B', 'C', 'F', 'G', 'H', 'I', 'J', 'L', 'N', 'O', 'P', '../../../sourced_images/fungesFull-square.svg', '../../../sourced_images/shrimp-895011_1920-3-coloured.png', '../../../sourced_images/soup-576424-woodBowl2.svg', '../../../sourced_images/turkey-151756-square.svg', '../../../sourced_images/spare-ribs-575310-noPlate2.svg', '../../../sourced_images/salmon-575539-square.svg', '../../../sourced_images/pret_2-1024-square.png', '../../../sourced_images/strawberye-2-square.svg', '../../../sourced_images/gyngerbrede-brownieBase1-square.svg', '../../../sourced_images/meadMug-2.1-square.svg', '../../../sourced_images/pote-copos-singleCup-3.2.svg', '../../../sourced_images/container-41935.svg', '16']
2022-11-09 17:37:58 - DEBUG - create_output_file:734 - output file name is menu_P-generated
2022-11-09 17:37:58 - DEBUG - remove_empty_texts:809 - Removed 0 empty texts items
```

The images are a combination of SVGs and PNGs. I've manually edited the image links to use full variable paths for example:
`%VAR_appetiser_image1% = ../../../sourced_images/shrimp-895011_1920-3-coloured.png`

In the first image below you can see the third row, third column is selected but no image shows (I assume due to scaling).
In the second image you can see just by toggling proportional the image appears and is scaled correctly.
The third image shows how the file was originally generated with several more "missing" images.
The fourth image shows the settings I'm using to export.

Thanks,

Derwent

![scibusIssue3](https://user-images.githubusercontent.com/1520613/200965580-fa6ebb44-2d62-4718-a2d0-d3a0d340017f.PNG)
![scibusIssue4](https://user-images.githubusercontent.com/1520613/200965583-41774296-a055-4235-bcb3-95b8e86bf295.PNG)

![scibusIssue5](https://user-images.githubusercontent.com/1520613/200966158-d0c0b2da-4ab1-4118-93bf-f1dab199c7f3.PNG)
![scibusIssue6](https://user-images.githubusercontent.com/1520613/200966614-d0596bb6-97b6-45c5-a9c9-b30e369e335b.PNG)

**Comment by berteh** [comment]
Hi Derwent.
First time in see such an issue... but let's figure it out.

Since the images adresses are properly replaced it dies not seem to be a problem in your template, nor data, nor SG, but rather in the way Scribus loads (or doesn't, actually) the images when opening the document.

Did you per chance notice if all the hidden images are of the same type (SVG maybe?). 

If that's the case, I would then guess Scribus makes an internal render of the vector file whenever an option is updated (resize, recheck 'fit to frame'...) that is missing from the SG-generated file.

We may then workaround the issue with a quick script that forces an update of all images.

If it's not related to a common extension might there be something else that distinguishes the hidden images (or their frames) from the visible ones?  Do the missing images always appear in the same frames ?

**Comment by drentsoft** [comment]
Hi,

I just checked and it seems to be mostly SVGs that exhibit the issue (and one png) but it's not the same ones in each generated file and not every SVG is showing the problem. While it does seem most problematic in the middle 2 rows, column 1 and column 3 I can't even pin point it to the image frame itself because some will be displayed correctly and some will not.

As you can see from the image below: 

- The image for C appears correctly on the right but not the left 
- the image for F appears correctly on the right but not the left
- The image for J appears correctly on the LEFT but not the right
- then the image for L doesn't display correctly in either file (or any of the files for that matter).

It's quite strange. I do wonder if it's a relative scale/DPI issue but I'm not sure how to check. The reason I think this is that image D always appears but with the bottom cut off, I think this is because the SVG is closest in size to the frame.

Thanks :) Yes I'm still working on wording for some things. Taster would be the best alternative to player in this case. 😃 

![scribusIssue7](https://user-images.githubusercontent.com/1520613/200977458-d4eb97cd-c5e3-41fe-b564-f4122f088c79.PNG)

**Comment by drentsoft** [comment]
AHA! I think I've worked it out! So. I "tested" the frames to get the initial paths that I could edit with the variables and in doing that each frame ended up with a wildly different scale/relative DPI scale. That must have been tripping up the auto-scaling in Scribus.

I reset them all to 437% X/Y DPI (which was the DPI that seemed to give the best results all around) and reran it and it's much better! Now I just need to work out how to centre the images in the frames instead of having them be top left aligned

![image](https://user-images.githubusercontent.com/1520613/201503868-60c75f28-bc03-4ff6-9293-77bbbd51e5f5.png)

![image](https://user-images.githubusercontent.com/1520613/201504115-6e252e99-4cfc-4a9a-bc98-b5b1dd70d79b.png)

**Comment by berteh** [comment]
maybe this script helps to automatically resize all images at once ?
it should have the same effect as re-applying the "fit to frame size + propotionally" option:

https://wiki.scribus.net/canvas/Scale_an_Image_to_Fill_a_Frame_Proportionally

**Comment by drentsoft** [comment]
Thanks for the script :)

**Comment by berteh** [comment]
I added your cards screenshot in the gallery at https://github.com/berteh/ScribusGenerator/wiki#other-games-cards 
if you'd like to take if off (or share some more/ related material for other to get inspiration) feel free to edit the page directly !
