### ISSUE TITLE
remove empty variables, empty lines & eol

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#21]
request from @garydale

is it possible to have the script remove variables (and eol characters?) that match empty .csv fields? It's not a big issue but with the .csv file having to contain all possible fields, I have to do a lot of deleting to clean up the output file. Deleting variable names requires me to select the name then hit delete, while deleting an empty line just requires a delete. Having the script remove empty lines would be even better.

**Comment by berteh** [comment]
good idea.

What would you consider best: to remove anything that resembles variable names (ie %VAR_*%), or only those that are found in the headers of the data file? I think the second is better as it looks less strict on what you can (or cannot) use in your scribus file... but it may seem strange to the user why some variables get removed and some not (if they are not in the data file).

Just to make sure: when you say "the script remove empty lines" do you mean: a line where you had a variable on the template, and was successfully substituted with empty text from the data?

**Comment by garydale** [comment]
On 13/09/15 03:25 PM, Berteh wrote:
>
> good idea.
>
> What would you consider best: to remove anything that resembles 
> variable names (ie %VAR_*%), or only those that are found in the 
> headers of the data file? I think the second is better as it looks 
> less strict on what you can (or cannot) use in your scribus file... 
> but it may seem strange to the user why some variables get removed and 
> some not (if they are not in the data file).
>
> Just to make sure: when you say "the script remove empty lines" do you 
> mean: a line where you had a variable on the template, and was 
> successfully substituted with empty text from the data?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/berteh/ScribusGenerator/issues/21#issuecomment-139910660>.
>
If the text is empty in the data, the variable is not replaced in the 
current Generator. The .sla file contains the variable name instead of 
the (empty) data. For me this is the worst case scenario.

So what I would be looking for is for the line the data would have 
occupied if there was any to be removed. That is, when the data field is 
empty, remove the line from the output file.

To give you an idea of the size of the problem, here is the XML schema I 
am using to get the conversion to CSV to put each XML field in a single 
CSV column. Most of the fields don't contain anything for any given club.

<!DOCTYPE clubs [
   <!ELEMENT clubs (club*)>
     <!ELEMENT club (clubname, clubnumber?, website?, charter?, region?, 
zone?, meetings?, den?, den2?, location?, location2, mailing?, 
mailing2?, mailing3?, clubemail?, title1?, incumbent1?, address11?, 
address12?, address13?, telephone11?, telephone12?, telephone13?, 
email1?, title2?, incumbent2?, address21?, address22?, address23?, 
telephone21?, telephone22?, telephone23?, email2?, title3?, incumbent3?, 
address31?, address32?, address33?, telephone31?, telephone32?, 
telephone33?, email3?, title4?, incumbent4?, address41?, address42?, 
address43?, telephone41?, telephone42?, telephone43?, email4?)>
       <!ELEMENT clubname         (#PCDATA)>
       <!ELEMENT clubnumber       (#PCDATA)>
       <!ELEMENT website          (#PCDATA)>
       <!ELEMENT charter          (#PCDATA)>
       <!ELEMENT region           (#PCDATA)>
       <!ELEMENT zone             (#PCDATA)>
       <!ELEMENT meetings         (#PCDATA)>
       <!ELEMENT den              (#PCDATA)>
       <!ELEMENT location         (#PCDATA)>
       <!ELEMENT mailing          (#PCDATA)>
       <!ELEMENT clubemail        (#PCDATA)>
           <!ELEMENT title1        (#PCDATA)>
           <!ELEMENT incumbent1    (#PCDATA)>
           <!ELEMENT address11     (#PCDATA)>
           <!ELEMENT address12     (#PCDATA)>
           <!ELEMENT address13     (#PCDATA)>
       <!ELEMENT telephone11     (#PCDATA)>
       <!ELEMENT telephone12     (#PCDATA)>
       <!ELEMENT telephone13     (#PCDATA)>
           <!ELEMENT email1       (#PCDATA)>
           <!ELEMENT title2        (#PCDATA)>
           <!ELEMENT incumbent2    (#PCDATA)>
           <!ELEMENT address21     (#PCDATA)>
           <!ELEMENT address22     (#PCDATA)>
           <!ELEMENT address23     (#PCDATA)>
       <!ELEMENT telephone21     (#PCDATA)>
       <!ELEMENT telephone22     (#PCDATA)>
       <!ELEMENT telephone23     (#PCDATA)>
           <!ELEMENT email2       (#PCDATA)>
           <!ELEMENT title3        (#PCDATA)>
           <!ELEMENT incumbent3    (#PCDATA)>
           <!ELEMENT address31     (#PCDATA)>
           <!ELEMENT address32     (#PCDATA)>
           <!ELEMENT address33     (#PCDATA)>
       <!ELEMENT telephone31     (#PCDATA)>
       <!ELEMENT telephone32     (#PCDATA)>
       <!ELEMENT telephone33     (#PCDATA)>
           <!ELEMENT email3       (#PCDATA)>
           <!ELEMENT title4        (#PCDATA)>
           <!ELEMENT incumbent4    (#PCDATA)>
           <!ELEMENT address41     (#PCDATA)>
           <!ELEMENT address42     (#PCDATA)>
           <!ELEMENT address43     (#PCDATA)>
       <!ELEMENT telephone41     (#PCDATA)>
       <!ELEMENT telephone42     (#PCDATA)>
       <!ELEMENT telephone43     (#PCDATA)>
           <!ELEMENT email4       (#PCDATA)>
]>

**Comment by berteh** [comment]
ok. will have a look. I'm just a bit afraid about "removing" elements automatically, in case they are referred to elsewhere... but will try anyway as it seems acceptable in the SLA.

**Comment by garydale** [comment]
Looking at the .sla file, I noticed that the %VAR_ substitutions take the form of an <ITEXT /> element followed by a <para /> element when there is a new line to be created. The <para /> element describes the paragraph style for the <ITEXT /> preceding it.

A simple rule would be that if the <ITEXT /> contains a %VAR_, remove it. If the following element is a <para />, remove that too.

I gather that your script currently doesn't know if it is doing replacements or not, so you may want to rescan the output for those conditions before appending or creating the output file.

**Comment by berteh** [comment]
being worked on.

for documentation purpose: how I intend to clean the SLA (before pdf generation)

1. cleaning text in which some variable is not substituted (ie: known or unknown variable):

    <ITEXT CH="empty %VAR_empty%  variable should not show" FONT="Arial Regular" />

2.  removing any empty <ITEXT@CH> after step 1

3. remove any <PAGEOBJECT> that has no <ITEXT> child left

**Comment by berteh** [comment]
implemented in  a9ba67e

**Comment by berteh** [comment]
related documentation at https://github.com/berteh/ScribusGenerator#clean-output
