### ISSUE TITLE
Fetching an image into an image frame in Scribus and export it as a new layer in the generated the PDF file.

### ISSUE THREAD

**Issue by emtmedia** [berteh/ScribusGenerator#211]
Hi there.
I've been testing ScribusGenerator to fill out the fields of employee badges with text and an image, and I got it working fine.
However, when it generates the PDF file as per my choice in the plugin UI window, the output PDF file is completely flattened, in such a way that I cannot move the image around to slightly adjust it manually to perfectly match its position within the image frame.
Is there a way to tweak the plugin code so that instead of generating an all flattened PDF file, create another layer for the image on top of the written fields layer? Like, including a toggle switch in the UI window to turn the feature on and off.?
That way, the fetched image would float around over the fields and I could adjust it manually to position using a regular PDF reader program to do so. Thank you beforehand!!!

**Comment by berteh** [comment]
Hello emtmedia.

From my experience Scribus (the editor, not Scribus Generator) provides quite a few good options to place images&pdfs, floating, flowing text around (easier across layers) or within, aligning, sizing, cropping, deforming, colouring, rotating, you name it... even all at once. And Scribus Generator can automate most of these dynamically (eg change angle of rotation, level of zoom, center of cropping, shade of colour...). 

If you position your image is in another (top?) layer in the template SLA file, the generated SLA will preserve the very same structure.

I would thus suggest to use Scribus Generator to create a SLA file, not PDF, and the fine tweak the generated SLA to suit you needs in Scribus... and simply click 'export to PDF' when you're happy.
Maybe this helps :
https://wiki.scribus.net/canvas/Working_with_image_frames

As for the generated PDF being flattened, that is all depending on the settings in Scribus (again: editor, not Generator), and you should ask their user forum or mailing list as I'm no specialist there... but any option Scribus can handle can be used just the same in SG.

Good luck.
would gladly take a peak at the result of you feel like sharing 😄

Berteh.

**Comment by emtmedia** [comment]
Hi there Berteh.

Thank you very much for your quick response, your suggestion seems to be
very helpful. I'll put it in practice and see the outcome! Thanks again.
Kind regards.

Elton Miranda Tavares

**Comment by berteh** [comment]
did you find a solution that works for you ?
