### ISSUE TITLE
Scribus Generator not working

### ISSUE THREAD

**Issue by AlphaX2** [berteh/ScribusGenerator#215]
Hello, 

I try to create a calendar / homework book so I created an CSV file containing all the relevant data, but in my litte test/example file just three(!) of 14 fields get filled, but I don't know why.

I also tried to use CLI, with the same result. (Test__single.sla)

So hopefully, I want to ask for help.

Working on Fedora 38 / Scribus 1.5.8 / Python 3.11.4.
Edit: Business Cards example worked as expected.

[Test.zip](https://github.com/berteh/ScribusGenerator/files/12320062/Test.zip)

**Comment by berteh** [comment]
I'll have a look at your test file in the next days.
At first glance I see no reason in the data or VAR_ use that poses any problem.

**Comment by berteh** [comment]
sorry for *very* late answer. I just spotted your open issue while doingcleanup, very sorry.

Your template file contains a lot of hidden character (soft hyphen) that do not show in Scribus, and as they are hidden withing the variable names, those names do not match the data column name anymore.

No clue how they got there (maybe a copy-paste from other software, Word being usual suspect), for instancer there are 2  in 
%VAR_**&#173;**mon**&#173;**tag.

If you get rid of all of them everything works just fine.

I'll try to print some warning for unfound variables to make such issues easier to spot.... in the meantime I'd be interested to know how you created this template... to find the source for these characters. any idea (even if it's quite some time ago) ?
