### ISSUE TITLE
Help wanted. Add Danish and German æ, ø, å and ä, ö

### ISSUE THREAD

**Issue by Kilo8686** [berteh/ScribusGenerator#219]
Hi
I am running Scribus 1.5.8 + the 1.5.6+ ScribusGenerator.py    trying to do "mail merge" / data merge.

When using danish / german words containing "special symbols" the script won´t run.

Is there a way that these special symbols can be added so the script can run?

Thank you very much :)

**Comment by berteh** [comment]
looking into this now. sorry for late answer.

**Comment by berteh** [comment]
works for me just fine out of the box using Scribus 1.6.1 in Ubuntu, and a CSV data file generated with all default settings by LibreOffice.

I could use all of the character both in static text frames in the template, and in the dynamic texts data in the CSV file:
![image](https://github.com/berteh/ScribusGenerator/assets/36950/d989be7f-5970-4bea-baad-fcb25315193c)

Please update script and try again, kindly attach your sla and csv file if you still meet the issue.
