### ISSUE TITLE
ModuleNotFoundError: No module named 'Tkinter'

### ISSUE THREAD

**Issue by ignutanz** [berteh/ScribusGenerator#220]
Trying to run ScribusGenerator in Scribus. The following error occurs:
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 21, in <module>
ModuleNotFoundError: No module named 'Tkinter'
```
installed python3-tk, still problem persists

**Comment by berteh** [comment]
What's your OS?

as far as I know the default python+tk install works out of the box on most Linux and Windows, but not MacOS.

If you run MacOS I recommend using only command line version of ScribusGenerator. It supports all the same features, just from the command line... and thus does not require tK module.

Kindly let me know if you manage to get the GUI on Mac!

**Comment by smagyarown** [comment]
I'm using Windows 10. It was working about a month ago when I was making raffle tickets, but this morning it started throwing those same errors. I did update Scribus when I worked on the tickets then, but it wasn't an issue.

**Comment by ignutanz** [comment]
It worked when i used the python3 version

**Comment by rafo** [comment]
@ignutanz:

> It worked when i used the python3 version

Please explain, since I have the same problem.

**Comment by ignutanz** [comment]
> @ignutanz:
> 
> > It worked when i used the python3 version
> 
> Please explain, since I have the same problem.
Use this version since you might be using Python3
[https://github.com/berteh/ScribusGenerator/archive/python3.zip](https://github.com/berteh/ScribusGenerator/archive/python3.zip)
