### ISSUE TITLE
Is it possible to print %VAR_COUNT%, also noted the duplication of a last entry in .csv

### ISSUE THREAD

**Issue by sersha** [berteh/ScribusGenerator#225]
I had a need to produce some numbered tickets, many on the same page, and used SG for the purpose. It worked well enough, taking a sequence from a data file (1..N), although the very last number repeated a few times, filling the remaining tickets on the page. No big deal, but it would be nice if the program stop when reaching the last entry in the data file.
I also noticed, that there is a variable %VAR_COUNT%, which could be used for the file naming. That would be also useable for numbering, but when I tried it in the source file, it printed nothing. Would be nice to have access to it, too.

Enclosed are .sla test file, and simple data file.
Last but not least, thanks a lot for the wonderful and valuable script. I used it earlier for making diplomas for the musical school and musical festivals.
[testseqnumbering__single.pdf](https://github.com/berteh/ScribusGenerator/files/15148822/testseqnumbering__single.pdf)
[testseqnumbering.csv](https://github.com/berteh/ScribusGenerator/files/15148829/testseqnumbering.csv)
[testseqnumbering.sla.zip](https://github.com/berteh/ScribusGenerator/files/15148835/testseqnumbering.sla.zip)

**Comment by berteh** [comment]
done. please check. thanks for your feedback.
