### ISSUE TITLE
Bug: Last row duplicates to fill the remaining placeholders in the template when using SG_NEXT-RECORD

### ISSUE THREAD

**Issue by ignutanz** [berteh/ScribusGenerator#227]
I have a csv file with a 13 record data. with the last being the total.
I create a scribus template having a table of 7 rows with the first column of each row starting with %SG_NEXT-RECORD% to load the data from the csv on the same page on each row. I find that in the generated output, the first page goes correctly with the first 7 records from the csv. the second page has the next 6 records but **the last row being repeated.**. The last row of the csv is used to fill the remaining rows in the template even after the last record in the CSV is reached. How can i stop filling the data once the last row in the csv is reached.

**Comment by sersha** [comment]
I have had the same problem, noted in the entry #225 .

**Comment by berteh** [comment]
This behaviour is a expected.
The last row is currently being used to fill all remaining "spots" until all items needed by the current template are replaced.

It made sense from a more "graphical" perspective, as to avoid getting lots of empty slots in a partially filled template... possibly even breaking the result layout if you rely on non-empty data (such as image placeholder, dynamic sizes or others). 

That being said I see no problem in changing this default behaviour to replace all exceeding placeholders with an empty value. Having a look at it now, will let you know once done.

**Comment by sersha** [comment]
Thanks! I got your point. I think, it would be great if you publish this information for all.But perhaps, an option to choose one way or another would be great.
And again, my heartfelt appreciation for your work!Best regards, Sergey

    On Saturday, June 8, 2024 at 01:58:48 PM GMT+3, Berteh ***@***.***> wrote:  
 
 


This behaviour is a expected.
The last row data is currently being used to fill all remaining "spots" until all items needed by the current template are replaced.

It made sense from a more "graphical" perspective, as to avoid getting lots of empty slots in a partially filled template... possibly even breaking the result layout if you rely on non-empty data (such as image placeholder, dynamic sizes or others).

That being said I see no problem in changing this default behaviour to replace all exceeding placeholders with an empty value. Having a look at it now, will let you know once done.

**Comment by berteh** [comment]
done. please check. thanks for your feedback.
