### ISSUE TITLE
Allow the CLI to generate PDFs

### ISSUE THREAD

**Issue by chevdor** [berteh/ScribusGenerator#228]
The GUI, while nice for a first run, it rather heavy to use and there are bugs (such as the separator not being saved or loaded properly from the config).

I would rather use the CLI and have all those setting in a script I can manage.

But for this, the CLI would have to offer the PDF generation. Would that be possible ?

**Comment by berteh** [comment]
it's already possible using https://github.com/berteh/ScribusGenerator/wiki/Running-Scribus-Generator-from-the-command-line#generate-pdf-from-command-line

even though it's command-line based this script runs the full Scribus app, not headless.

...and you may be interested in the reverse: command-line pdf to sla described in #198 

I hope this works for you !
