### ISSUE TITLE
Color not replaced

### ISSUE THREAD

**Issue by magjo** [berteh/ScribusGenerator#229]
I cannot get replacement of colors to work.

Steps I have performed:

- I have a column in my CSV file named Color1
- I have a Solid color named %VAR_Color1% in my Scribus document and multiple other colors like "Blue", "Green"
- I have set the background color of a polygon and the text color of some text to %VAR_Color1%. This can be seen if I open the document with a text editor. I a have a text field with the text %VAR_Color1%.
- I run the Scribus Generator script without errors, creating only Scribus files.
- The background color of the polygon is white and the text is black, not using my created colors Blue or Green. The text field however is changed to the text "Blue" or "Green" correctly. All other variables in text are also replaced correctly.
- If I look into the generated document using a text editor I can see the PColor attribute of the polygon is empty ("").

I'm very new to both Scribus and Scribus Generator, so I might be doing something wrong, but I think I've got it all right.

The document, the CSV file and an example of a script generated file are attached in the zip file..

[Colorbug.zip](https://github.com/user-attachments/files/15746500/Colorbug.zip)

**Comment by berteh** [comment]
hello and thanks for the feedback.

I see the name of your dynamic color %VAR_color1% has a small case "c" in the SLA template, instead of the capital "C" used in the data and text frame... that may be part of the issue.

**Comment by berteh** [comment]
besides the above problem I did spot an issue with your data (CSV) file :

It seems to have been created/encoded in some way that did lead ScribusGenerator to break the reading/parsing of that data, prepending a \ufeff byte before the header line.

I'm looking into it now... but just so I can understand: how did you create this CSV file please ? (what software+OS+settings if any) ?

FYI (and my personal notes) the header of data file has been parsed into %VAR_\ufeffNumber;Bibnumber;Class;Col1% ... and that definitely will not work. likely related to BOM UTF-8/UTF-16:  https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string

**Comment by berteh** [comment]
indeed once both the (minorcase) name and CSV format issue are fixed the script works:
![image](https://github.com/berteh/ScribusGenerator/assets/36950/7df9c05a-6b77-4952-a0c6-720d67b96565)

so I'm really interested in knowing how you created that CSV file... please 
[Colorbug_fixed.csv](https://github.com/user-attachments/files/15748246/Colorbug_fixed.csv)
[Colorbug_fixed.sla.txt](https://github.com/user-attachments/files/15748247/Colorbug_fixed.sla.txt)
;)

**Comment by berteh** [comment]
Turns out this encoding byte is not leading to any error, so I will disregard it unless you come back with contradictory information.

To get your original CSV data to work (after fixing color name) you just need to make sure to mention the proper "semicolon" separator character, instead of the default "comma":

![image](https://github.com/berteh/ScribusGenerator/assets/36950/16cf5703-e398-4c6d-be1b-4d11ad17178d)

have fun, and don't hesitate to share your work in the gallery : https://github.com/berteh/ScribusGenerator/wiki#gallery-of-examples--some-templates

**Comment by magjo** [comment]
Thanks for your quick response!

I used Excel (latest version I think) on Windows 11, with Swedish settings. The original csv file included some Swedish characters (å and ö), which I replaced in case that was the cause (Blue was Blå, and Green was Grön).

**Comment by magjo** [comment]
I got it working by just changing %VAR_color1% to %VAR_Color1%.

Sorry to take up your time with a typo. I am very thankful for your quick and friendly help!

**Comment by berteh** [comment]
great. by the way: sweedish characters should work without problems. I tested it in data and template at least... not in variables names yet, but it should be ok.
