### ISSUE TITLE
Missing document

### ISSUE THREAD

**Issue by mrjoebosch** [berteh/ScribusGenerator#233]
Hi,

i'm trying to use the scribus generator. in your manual there's a link to an exmaple document for multiple records on a single page that gets a 404.
Could you please store the file again?
That would be great!

Thanks,

Jeroen

<img width="763" alt="2024-09-01_19h08_19" src="https://github.com/user-attachments/assets/b867bd3a-8413-4dce-bdaf-c1de0692be9a">

**Comment by berteh** [comment]
Will do. In the meantime you can find other examples and explanations in the will: 

https://github.com/berteh/ScribusGenerator/wiki/How-to-use-%25SG_NEXT-RECORD%25

**Comment by mrjoebosch** [comment]
Thank you,

think this could already help!


Bierlinie GmbH
Wupperstr. 10
14167 Berlin



------ Originalnachricht ------
Von "Berteh" ***@***.***>
An "berteh/ScribusGenerator" ***@***.***>
Cc "mrjoebosch" ***@***.***>; "Author" 
***@***.***>
Datum 01.09.2024 21:19:04
Betreff Re: [berteh/ScribusGenerator] Missing document (Issue #233)
