### ISSUE TITLE
Feature Request: Single Document Creation with GUi/wizard

### ISSUE THREAD

**Issue by psit** [berteh/ScribusGenerator#27]
Hi!
A great feature to improve your Generator Script and Scribus as a whole would be to offer a GUI to insert data for a single document (corresponding to a single line in the CSV). The effort to create a CSV for a single document is quite annoying and the usecase should be common.

This feature would be a benefit for several reasons:
1. Variables can be used in a way (even much more powerful) like text variables are used in Adobe InDesign (in opposition to "mail-merge" functionality this is useful for the creation of single documents based on a template with some variable content like magazines/periodic newsletters with variable release date, issue number, etc.)
2. It allows to create single items from a mail-merge batch. E.g. creating business cards for the whole staff of 100 employees and later recreate single cards for individuals (e.g. new employees).
3. Allows to easily create a "preview" of a single item before batch-creation of a mail-merge job.

My personal need is case no. 1 - I'm used to work with InDesign. In my workflow I open the template to create the new document, edit the variables for issue number and release month and start filling the content. To achieve the same in Scribus I would need to edit the CSV for a single line containing the data of the current issue, then create the document from the template with script generator. 
For the data of a single line in the CSV, a wizard like GUI would be great as it avoids the need for the external data source.

Kind regards and thanks for your great work!
Peter

**Comment by berteh** [comment]
hi Peter.
good idea. 
Do you know any Tkinter widget/component that I could use for such a purpose easily?
B.

**Comment by psit** [comment]
Hi B.
I'm sorry I have absolutely no clue about Python and Tkinter. I could do it in Java/Swing, but I could think of something like a partially editable table. First the document needs to be parsed to get all variable names. Then an editable table can be filled with the variable names, offering the possibility to enter values for the variables. Ideally the previously entered values would be stored (maybe in the document/template, but I don't know how to do that, as I don't know anything about the document structure. Maybe some comment/property could contain the data in JSON style).

**Comment by berteh** [comment]
wrong reference in last post. will try to implement this next.

**Comment by berteh** [comment]
still like the idea but will definitely not find the time to work on it. if anyone wants to give it a shot feel free to submit a PR !
