### ISSUE TITLE
Scribus Generator in non-interactive mode

### ISSUE THREAD

**Issue by kavirajk** [berteh/ScribusGenerator#3]
I would like to automate the creation of photobook from scribus template. Though scribus generator does the job, I don't want to manually open scribus generator each time I want to generate pdfs. It there any way to run scribus generator to run non interactively so that I can automate programatically??

**Comment by berteh** [comment]
Good idea, I'll have a look and come back to you in the next days.

**Comment by luzpaz** [comment]
@berteh This would be quite useful especially if you conducted the conversation on the scribus Mailing list lists.scribus.net there are many python users there and there was a recent push to run Scribus via the CLI to execute Python scripts.

**Comment by berteh** [comment]
ok. preferably scribus or scribus-dev?

**Comment by luzpaz** [comment]
scribus-dev most likely

**Comment by berteh** [comment]
Scribus Generator now generates SLA files from the command line too, see https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line

no pdf generation there so far. help is welcome to make this happen if you know how.

**Comment by berteh** [comment]
pdf generation from command line will not happen in Scribus 1.4.x, due to restrictions on the API. But you can now use the [Scribus Generator from the command line](https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line) to generate your SLAs.

Kindly test it  @kavirajk, and let me know any relevant feedback!  (or even add to the [wiki](https://github.com/berteh/ScribusGenerator/wiki) how you use this in combination with other tools)

**Comment by troybail** [comment]
While attempting to run from the CLI in PowerShell using the first syntax format (SCRIBUS_Command SLA) I get the following error.  

`PS C:\Users\Troy\Desktop\FlashCards_Scribus> C:\Users\Troy\Dropbox\Apps\Scribus\Scripts\ScribusGenerator\ScribusGeneratorCLI.py .\set1.sla
Traceback (most recent call last):
  File "C:\Users\Troy\Dropbox\Apps\Scribus\Scripts\ScribusGenerator\ScribusGeneratorCLI.py", line 124, in <module>
    generator = ScribusGenerator(dataObject)
  File "C:\Users\Troy\Dropbox\Apps\Scribus\Scripts\ScribusGenerator\ScribusGeneratorBackend.py", line 74, in __init__
    os.path.abspath(os.path.dirname(__file__)), 'logging.conf'))
  File "C:\Python37\lib\logging\config.py", line 79, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "C:\Python37\lib\logging\config.py", line 145, in _install_handlers
    h = klass(*args, **kwargs)
  File "C:\Python37\lib\logging\handlers.py", line 145, in __init__
    if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'`

**Comment by berteh** [comment]
Hello.

The error message points to a configuration error in the logging.conf file.

Could you please check it out, look up its syntax online... And copy its
content here if you find nothing?

Have a nice day.
