### ISSUE TITLE
Logger config error leads to silent crash

### ISSUE THREAD

**Issue by superdweebie** [berteh/ScribusGenerator#37]
Hi there, I have followed the instructions carefully, but I just can't get the script to work. Scribus 1.4.5. Very simple template file - just one text element, very simple csv file - just one column, three rows. I get the script GUI and press 'generate' and nothing happens. I'm sorry I can't give a more specific error, but it is just a silent fail.

**Comment by berteh** [comment]
Hello @superdweebie, sorry to read it didn't work out of the box for you.

- What OS are you using? I tested it just fine in Ubuntu and Win8, with Scribus 1.4.5.
- Did you try to run the example "business card" file (sla and csv) from the script example directory?

ScribusGenerator records all its actions in a log file located in its own directory, could you please copy-paste the content of scribusGenerator.log in this issue report?   If you don't find it simply change the settings of logging.conf [handler_file] section to locate the .log file in your desktop directory... and run the script again.

I hope we can make this work for you!
have a nice day.
B.

**Comment by superdweebie** [comment]
Hi @berteh, thanks for your quick reply. Your suggestions have helped me solve the problem. You asked me to look for a log file, and there wansn't one. I realised it is because I'm using windows 10 and  used the scribus installer, so scribus is in `c:\program files\scribus 1.4.5`. Trying to be neat, and following the ScribusGenerator readme, I placed ScribusGenerator in `c:\program files\scribus 1.4.5\shared\scripts\`. However, as a windows security thing files can't be modified in `c:\program files\` without admin permission. So... I moved ScribusGenerator to a different location that doesn't need admin rights, and now it all works perfectly.

Thanks!

**Comment by berteh** [comment]
I add a few things I may (maybe) do to improve this issue overall (it's not high on my priority list though), feel free to submit code push that implements this!

1. display log in "console-like" display, to show things move (or not).
1. detect write-only dirs, issue a warning (todo: see how python.logging handles handlers errors)... and still generate (just disable that handler)

**Comment by superdweebie** [comment]
Great suggestions @berteh . I'm not an experienced python hacker, but I might have a dig and attempt the fix you suggest.

**Comment by berteh** [comment]
Thanks @superdweebie, that would be fantastic.

If your not familiar with git(hub) the easiest would be to fork this project, create a new branch (named eg "log-location-fix"), do any code change you like in that branch (committing to git) and do a "pull request" from github, so I can be notified of what you're doing and we can discuss details if you want to. All explained much better in https://guides.github.com/activities/forking/

B.

**Comment by superdweebie** [comment]
Thanks @berteh. I know git and github well, it's python that I'm not great with. The last python I wrote was about four years ago.

**Comment by berteh** [comment]
Then if you feel like it by all means try, I'd be glad to help if I can ;)

**Comment by superdweebie** [comment]
By the way, do you intend to create a test suite? I find the best way to fix a bug like this is to write the test first - then you avoid regressions.

**Comment by berteh** [comment]
would be nice indeed. unfortunately I don't think I'll find the time any soon to do this for this (small side) project of mine.
I basically have 2-3 test settings I quickly test from GUI and CLI with both Scribus 1.4 and 1.5. It has been made easier since project settings can since last release be stored in the scribus template file. I´ll nevertheless add a feature request to not forget it.
