### ISSUE TITLE
support for \n \t and \v

### ISSUE THREAD

**Issue by RoleyBaxter** [berteh/ScribusGenerator#38]
Merging database field with pre-formatted text i.e. text with \n, \t, \v etc.etc. does not seem to work.
Gives ParseError : not well-formed (invalid token)

**Comment by berteh** [comment]
Hello @RoleyBaxter, thanks for this feedback.

Did you properly quote these data fields in you CSV? The following (with \n and \t in the "position field") works for me with no problem on the example/business-card.sla template:
```
name,position,email,logo,color1,color2,color3,font,top
John Doe,"Director
Financial Manager",john,sun.pdf,Blue1,Blue2,Blue3,Arial Regular,22.04
Jane Smith,"Director
Business Development",jane,moon.pdf,Blue1,Blue2,Blue3,Princess Sofia Regular,40.40
Ed Graham,"Assistant	engineer",ed,foot.pdf,Orange1,Orange2,Orange3,Arial Regular,22.04
Samuel Prot,"Assistant	marketing",sam,sun.pdf,Orange1,Orange2,Orange3,Arial Regular,22.04
Rachel Banks,"Assistant	finance",rachel,moon.pdf,Orange1,Orange2,Orange3,Princess Sofia Regular,40.40
```

Then there is the "problem" that Scribus does not handle these characters... so they simply get substituted by one space... but that at least leads to no error.

B.

**Comment by berteh** [comment]
closing for seems working fine and inactive issue... feel free to re-open if you experience the problem.

**Comment by berteh** [comment]
Hello @RoleyBaxter 
you can now have line breaks and tabs converted to scribus elements... provided your CSV is well-formed (see eg https://raw.githubusercontent.com/berteh/ScribusGenerator/linefeeds-tabs/example/Business_Card.csv)
Would you please test it for me and let me know if that works for you? it's for now in a separate branch: https://github.com/berteh/ScribusGenerator/tree/linefeeds-tabs

**Comment by RoleyBaxter** [comment]
Sounds great! I'll test and get back to you.

Den 2 apr. 2016 1:14 fm skrev "Berteh" <notifications@github.com>:
>
> Hello @RoleyBaxter
> you can now have line breaks and tabs converted to scribus elements...
provided your CSV is well-formed (see eg
https://raw.githubusercontent.com/berteh/ScribusGenerator/linefeeds-tabs/example/Business_Card.csv
)
> Would you please test it for me and let me know if that works for you?
it's for now in a separate branch:
https://github.com/berteh/ScribusGenerator/tree/linefeeds-tabs
