### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by jshackney** [berteh/ScribusGenerator#4]
Having trouble getting the script to work with OSX. Anybody else with similar issues? I've updated Tcl, not sure if I should up/downgrade my install of Python.

**Comment by berteh** [comment]
Hello jshackney.
So far I had no such feedback. Sorry to read it's not straightforward to you.

What issue do you encounter? If you run Scribus from the command line do you see any potentially useful message printed (error or other)?
B.

**Comment by jshackney** [comment]
Hello again,

I'm using Mac OSX with Scribus (1.5), and Linux with Scribus 1.4.

When I run ScribusGenerator on the Mac, the script will not execute. 
There is no window asking me to select files to 'merge'. The script 
simply fails to run.

When I run ScribusGenerator with Linux and the older version of Scribus, 
the script executes but it only generates a PDF for the last series of 
data. If I have five data sets, it skips 1-4 and creates a PDF for 5. 
Does that make sense?

The pastebin link below is a copy of the STDERR from OSX and Scribus 
1.5. I launched Scribus from the command line then executed the script. 
I can see that "an uncaught exception was raised" but it is not clear to 
me what caused the exception.

I'm mostly curious if you have encountered this behavior or have heard 
of it from any users. I'm not quite as familiar with Python or Scribus 
(and its API) as I should be. I believe something may be missing from my 
installation that is causing the uncaught exception, but I'm not certain 
where to start.

http://pastebin.com/37StPRKs (expires 23 JULY 2015)

**Comment by luzpaz** [comment]
@berteh what are the possibilities of you revising Scribus Generator to use something other than tkinter?

@jshackney next time post the pastebin without an expiration.

**Comment by berteh** [comment]
I'm open to any other option that tkinter. you have a preference? 

and if you can point me to the best way to initialize a file-chooser dialog in that favorite framework of yours with the path of the project currently open in Scribus even better!

**Comment by berteh** [comment]
@jshackney I guess it's a missing librairy in the python install on your system, unfortunately as I came to this post too late I could not read your log... figured a solution already?

**Comment by suburbanworrier** [comment]
I've spent some time trying to get sg to run on my Mac without success. There are various threads about tkinter breaking some of the shipped plugins on Mac.
If you made the plugin so it accepted arguments on the command line wouldn't that open it up to other frontend contributions?

**Comment by berteh** [comment]
ok. will look making this work from command line in the next days.

**Comment by berteh** [comment]
Scribus Generator now generates SLA files from the command line too, hopefully that works with Mac. see https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line

no pdf generation there so far. help is welcome to make this happen if you know how.

**Comment by berteh** [comment]
@suburbanworrier @jshackney full command line support is now available (sla generation only though). Allows to use sg in Mac without Tcl. Let me know how that works for you.

doc:  https://github.com/berteh/ScribusGenerator#running-scribus-generator-from-the-command-line

**Comment by luzpaz** [comment]
@berteh awesome! can you provide some orientation in the docs about this: https://github.com/berteh/ScribusGenerator#macosx-troubleshooting 
Thanks!

**Comment by berteh** [comment]
@luzpaz I don't know what to say more besides what already in https://github.com/berteh/ScribusGenerator/blob/master/README.md#mac-osx-troubleshooting
any idea?

since I don't have a mac I cannot provide more direct guidance there.

**Comment by luzpaz** [comment]
@berteh apologies. I read it wrong. It seems you do offer a way to circumvent issues in OSX via the command line without a need for tkinter.

**Comment by berteh** [comment]
@luzpaz no appologies needed, the command line is quite new. I hope it works fine for you. any suggestion/request to improve is welcome.
