### ISSUE TITLE
Support for more complex data patterns/sources

### ISSUE THREAD

**Issue by animeshpathak** [berteh/ScribusGenerator#41]
Bonjour @berteh :

We were very happy to find this tool, since we want to use templates to print out work orders for cars in particular formats, and wanted to give our admins the ability to edit templates in a WSYIWIG manner.

I'd love to discuss this more with you, including a possible paid contract. Please drop me a line at `animesh@mykaarma.com`.

Thanks,
Animesh

**Comment by berteh** [comment]
Dear @animeshpathak,
thanks for getting in touch. You got an email. 
B.

**Comment by animeshpathak** [comment]
Thanks B. Will send you my specs soon.

**Comment by berteh** [comment]
Hello @animeshpathak 
Haven't read from you since... Still need some help or did you choose another way?
B.

**Comment by animeshpathak** [comment]
Hi @berteh ; my bad for not getting back. We decided to go with XSL-FO for now, and that worked for us.

Keep up the good work!

**Comment by berteh** [comment]
Glad you found a solution for your needs.
Out of curiosity: what wysiwyg component/interface did you find/select for a xsl-fo toolset?
have a nice day.
B.

**Comment by animeshpathak** [comment]
We didn't go WYSIWYG; the developers decided to use the text editors :)
