### ISSUE TITLE
logging.conf issue in Gentoo

### ISSUE THREAD

**Issue by berteh** [berteh/ScribusGenerator#42]
reported by Alan at http://forums.scribus.net/index.php/topic,1965.0.html

I'm trying to use Scribus Generator to add addresses to a newsletter and have been working my way through error messages (Tk not compiled into Python, etc.) but now it's just hanging when I tell it to generate.

The script is in my user directory and permissions seem OK, user has read/write to directory and files.

Scribus 1.5.2.svn
Python 2.7.10 (3.4.3 is also installed and is the system default)
Gentoo Linux

It seems like it may not be parsing logging.conf but I don't do Python, so I'll leave it to the experts. By running Scribus via console and running the script, I get this error message:

```
Exception in Tkinter callback
Traceback (most recent call last):                                                                       
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1536, in __call__                                 
    return self.func(*args)                                                                             
  File "/home/alan/Downloads/ScribusGenerator-master/ScribusGenerator.py", line 147, in buttonOkHandler 
    generator = ScribusGenerator(dataObject)                                                             
  File "/home/alan/Downloads/ScribusGenerator-master/ScribusGeneratorBackend.py", line 56, in __init__   
    logging.config.fileConfig("logging.conf")                                                           
  File "/usr/lib64/python2.7/logging/config.py", line 77, in fileConfig                                 
    formatters = _create_formatters(cp)                                                                 
  File "/usr/lib64/python2.7/logging/config.py", line 113, in _create_formatters                         
    flist = cp.get("formatters", "keys")                                                                 
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get                                         
    raise NoSectionError(section)                                                                       
NoSectionError: No section: 'formatters'
```

**Comment by berteh** [comment]
Hi Alan.

I hope we can track and fix your problem here on github, as it's easier for me to get all matters relating 
to this script in a single place.

Now for the problem: [some googling](http://stackoverflow.com/questions/7922602/python-2-4-3-configparser-nosectionerror-no-section-formatters) on the same topic led me to the fact this error message may be misleading and could relate to the logging.conf file not being found. Could you please try to make its path absolute in [l.58 of ScribusGeneratorBackend.py](https://github.com/berteh/ScribusGenerator/blob/master/ScribusGeneratorBackend.py#L56), changing ```logging.conf``` with ```/home/alan/Downloads/ScribusGenerator-master/logging.conf```

Let me know if that works around the problem... or if we have to look elsewhere.

It does not seem to me to be a problem of the content of loggin.conf, as this works on others OS just fine (Ubuntu, Xubuntu, Windows, Mac).

B.

**Comment by aardwolfweb** [comment]
Hi,
Thanks for the hint. Replacing logging.conf with an absolute path does indeed work. I've attached a small patch that should work. I'm not sure if this the best method in Python, it's how I would fix the problem in PHP.

Thanks for your help!

-Alan

[ScribusGeneratorBackend.txt](https://github.com/berteh/ScribusGenerator/files/154107/ScribusGeneratorBackend.txt)

**Comment by berteh** [comment]
Thanks @aardwolfweb for the patch.

As I cannot reproduce the issue, could you please try another fix for me, that I'd prefer using if it works: simply add an empty (text) file named ```__init__.py``` (please make sure there is no invisible .txt extension left) in the ```/home/alan/Downloads/ScribusGenerator-master/``` directory... and leave the relative path (simple "logging.conf", without your hack).

It might work and would feel cleaner. Thanks!

**Comment by aardwolfweb** [comment]
No, sorry, that still gives the same error.

**Comment by berteh** [comment]
thanks for trying! will integrate your patch in the code.
