### ISSUE TITLE
Trouble with special characters in CVS files

### ISSUE THREAD

**Issue by tecknos11** [berteh/ScribusGenerator#43]
If I include special characters in the .cvs documents like "•", I get an error. I have attached the ScribusGenerator log file and appended the text of the error that I got in the error prompt. I was using Scribus 1.51
[LogNError.txt](https://github.com/berteh/ScribusGenerator/files/191224/LogNError.txt)

**Comment by berteh** [comment]
full utf-8 charset should be valid, except maybe for some characters that are not allowed in xml such as  backspace U+0008 (see https://www.w3.org/TR/xml/#charsets).

Are you sure your source cvs file is saved in utf-8 encoding? how do you create/edit it? MSOffice's Excell is known to create poor utf-8 files. I've had good results re-saving such files with notepad++, or simply using OpenOffice or LibreOffice.

**Comment by tecknos11** [comment]
After doing a bit more trouble shooting than I did last time, the script worked as intended. The problem was both character encoding and some kind of .cvs document issue.

Part 1: Encoding error
 Before posting my issue I couldn't get the full spreadsheet, that I had converted from an excel file to a .cvs file, to work with the script. To get it working, I cut out most of the file, stripped the file of all special characters using Notepad++ and then converted everything to UTF-8. To test to see if the problem was special characters, I used Excel to paste a bullet point into the sheet. When the bullet point was in the document the document broke. As it happens, Excel also played a part in allowing the bullet point to cause the error by reconverting the document back to ANSI. The bullet point does work with UTF-8. 

Part 2: Formating error
As it happens, in addition to Excel, Libre Office and Google spread sheets is also bad at converting excel files to .cvs because they both allow a formating error to occur. `"Actinopterygii: Neopterygii (""new"" ""fins"")",,,,,,,` Once I took out the extra quotes I was fine and no errors. Now, if only I could keep the line breaks and tabs.....

**Comment by berteh** [comment]
Thanks for the info. 

When I want a special character I copy-paste it form one of the many online UTF-8 characters tables. They even include funny weddings, arrows of all kinds and much more.

Tabs and line breaks is more difficult, and a Scribus problem: how would you represent them in your final document? If it's an alignment issue (most tabs are) then decomposing this text in multiple data fields may be an option, or replacing each tab with a few non-separatable spaces.

AFAIK scribus handles line breaks as new paragraphs, but if you know a way to get a simple line break inside a text frame tell me, I could then look into replacing line breaks accordingly.

**Comment by berteh** [comment]
you can now have line breaks and tabs converted. 
Would you please test it for me and let me know if that works for you?  it's for now in a separate branch: https://github.com/berteh/ScribusGenerator/tree/linefeeds-tabs

**Comment by tecknos11** [comment]
I will do that...before I was having to hack scribus a bit by changing

On Fri, Apr 1, 2016 at 4:12 PM, Berteh <notifications@github.com> wrote:

> you can now have line breaks and tabs converted.
> Would you please test it for me and let me know if that works for you?
> it's for now in a separate branch:
> https://github.com/berteh/ScribusGenerator/tree/linefeeds-tabs
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/berteh/ScribusGenerator/issues/43#issuecomment-204603732>
>



-- 
========
Kent Schneider

**Comment by tecknos11** [comment]
I will do that...before I was having to hack scribus a bit by changing

> hello

hello

to

> "/><para ch="hello" />

<para ch="hello" />


On Mon, Apr 4, 2016 at 10:58 AM, Kent Schneider <kjis2005@gmail.com> wrote:

> I will do that...before I was having to hack scribus a bit by changing
>
> On Fri, Apr 1, 2016 at 4:12 PM, Berteh <notifications@github.com> wrote:
>
>> you can now have line breaks and tabs converted.
>> Would you please test it for me and let me know if that works for you?
>> it's for now in a separate branch:
>> https://github.com/berteh/ScribusGenerator/tree/linefeeds-tabs
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/berteh/ScribusGenerator/issues/43#issuecomment-204603732>
>>
>
>
>
> --
> ========
> Kent Schneider
>



-- 
========
Kent Schneider

**Comment by tecknos11** [comment]
I will do that...before I was having to hack scribus a bit by changing the cells to include coding information. This is much better. Theoretically you could also also introduce things like __styling with markdown__ into the fray as well. I will let you know if anything breaks.

```
hello
hello
```
to
```
 "/><para ch="hello" />
<para ch="hello" />
```

**Comment by jvr14115** [comment]
Hi Berteh,
Im struggling to figure out how to work with unicode characters.
Regular bullets etc. all work fine. Now I have documents that use large circle (U9679).
If I enter this in Notepad++ directly, saved as UTF-8, it still appears as crossed square.
What am I doing wrong? Is it possible to write the bullet as kind of html code? If so, how should this be written?
Thanks in advance!

**Comment by berteh** [comment]
Hi @jvr14115 

Could you please next time start a new issue report instead of highjacking an unrelated one? Makes things easier for managing evt fixes. thanks!

That being said: UTF-8 is normally fully supported by Scribus (AFAIK). Are you sure the font you use in Scribus does support that particular character? On my UTF8 reference, the particular code you provided is not a large circle but a 陹 (https://www.fileformat.info/info/unicode/char/9679/index.htm)... and if such a character is missing from the font you use it is standard for most fonts to display a square instead of any missing character

So far I did not create a html entities encoding mechanism, as I thought UTF-8 support was preferable, so I'd rather find out why the uft-8 way does not work and fix it if necessary.

Could you provide me with a test CSV and Scribus template?

have a nice day.
