### ISSUE TITLE
Objects are incorrectly displaced vertically

### ISSUE THREAD

**Issue by stloeffler** [berteh/ScribusGenerator#46]
First of all: Thanks for your very useful script!

Recently, I ran into some trouble, however. Starting from [testcase.sla.txt](https://github.com/berteh/ScribusGenerator/files/276223/testcase.sla.txt), I used your script in "single file" mode (any csv with several lines will do - there are no variables to replace in the testcase). In the resulting [testcase__single.sla.txt](https://github.com/berteh/ScribusGenerator/files/276224/testcase__single.sla.txt), the blue box is increasingly displaced vertically on each consecutive page. 

I think I tracked this down. The testcase was created with a paper size of A4, which I later changed to A5 for the first (and only) page. The generator seems to use the document settings (ScribusGeneratorBackend.py@135) for calculating offsets (which are still for A4), not the settings of the actual page (which are A5). Interestingly, Scribus does not seem to follow the PAGEYPOS value when laying out the pages (there is no huge gap between them).

The background behind this is that I created a master-file with the same template adapted to different page sizes. I then took that, deleted all but one page, and saved that as template for ScribusGenerator. This is how I ended up with mismatching document/page settings.

I'm using Scribus 1.4.6 on Ubuntu.

**Comment by berteh** [comment]
hi @stloeffler , thanks for the detailed report and bug tracking. If you want to push a code change that fixes it please don't hesitate, otherwise I'll put in on my todo list to try and fix it.... but it's not likely to be really soon.

**Comment by berteh** [comment]
Hello Stefan,

Sorry for not looking into this earlier. The issue you raised is confirmed, and actually complex too, as it raises the question of handling documents with different pages dimensions in a single document.

I need to compute the (vertical and horizontal) offset of each duplicated object, for it is unfortunately not stored relative to the object's page in Scribus, but as an absolute value (i.e. relative to the document upper left corner). 

When using documents with pages of different sizes this gets quickly tricky (even though possible), and to keep the complexity to an acceptable level I nowadays "request" that the source document actually be comprised of only 1 "row" of pages, of any sizes and orientations you want, and that the document properties be set to the biggest of these formats. (That last bit is actually needed for Scribus to even display the pages right, AFAIK.) This constraint allows me to not bother about the horizontal offset, expanding generated documents only vertically, while still allowing for some flexibility in the number and size of pages in the source document. See the attached example source document (
[testcase_diverseSizes.sla.txt](https://github.com/berteh/ScribusGenerator/files/818927/testcase_diverseSizes.sla.txt)) and generated merged document ([testcase_diverseSizes__single.sla.txt](https://github.com/berteh/ScribusGenerator/files/818928/testcase_diverseSizes__single.sla.txt)).

In your case the document size (A4) don't match the actual biggest page of your document (A5), even though I understand this is a perfectly valid document.
I could handle this nicely by computing the height of the highest page in the source document, and use that as an offset... or stick to the current way of relying on the document properties (actually only it's height), which I find easier and clean.

So, if it's no big bother I'd prefer leaving these things as is, meaning you'd have to **change the document properties to match the biggest page in the document** (A5 in your case) for the generator to work. If it's important I can look into fetching the biggest height... or letting you push some code therefore if you feel like it (ScribusGeneratorBackend.py@159). 

If you see a better way of handling this any other suggestion is welcome too !
Let me know!
Berteh

**Comment by berteh** [comment]
suggestions are still welcome if you think of a better way to handle this.
