### ISSUE TITLE
Display a meaningful error message if a file can't be found

### ISSUE THREAD

**Issue by stloeffler** [berteh/ScribusGenerator#47]
If you specify a non-existent file as "Scribus File" or "Data File", a dialog with a lot of traceback information pops up. Ideally, the IOError should be caught and presented to the user in a nice and easy-to-comprehend manner.

**Comment by berteh** [comment]
I agree it would be much more user-friendly. If you want to push a code change that fixes it please don't hesitate, otherwise I'll put in on my todo list to try and fix it.... but it's not likely to be soon.

**Comment by berteh** [comment]
done. let me know if you need anything else.
