### ISSUE TITLE
It's not possible to use "Dynamic Colors" and "More advanced uses" while using Scribus 1.5.1

### ISSUE THREAD

**Issue by Erwinius** [berteh/ScribusGenerator#48]
Hi Berteh,

Firstly, what a fantastic tool did you create! Many thanks for that!

I Use to work with Scribus 1.4.6 but recently I started using Scribus 1.5.1. Main reason: The possibility to verticaly align text within a textbox.

But now i'm facing a problem with your ScribusGenerator. It's not possible to use "Dynamic Colors" and "More advanced uses" anymore. I'll give you a short description of what happens. I tried your business card example with both Scribus 1.4.6 en Scribus 1.5.1.

"Dynamic Colors" 
==============
%VAR_color1% is pink in the template. After generating 1.sla the color Blue1 became pink. So, it seems to be that %VAR_color1% is replaced by Blue1 and became pink in stead of using the color blue.

"More advanced uses"
==================
Using SGAttribute there's nothing happening at all. No error, and also no change in Font.

Are you familiar with the problem? Am I doing something wrong? Is there a sollution for these problems?

I hope to hear from you. 

Once again, thanks again for this good job!

Greatings
Erwinius

**Comment by berteh** [comment]
Hello @Erwinius 
Thanks for the kind words, it's always appreciated to read someone else finds my works interesting.
Tthe issues you mention are due to some changes in file format between scribus 1.4 and 1.5 branch. As the 1.5 format is not fixed yet I was not planning to support each version... and was planning to wait for v1.6 release.
I'll nevertheless have a quick look, at least for the dynamic colors, and let you know if I fix it.
B.

**Comment by berteh** [comment]
please try with scribus 1.5.2, I just did and it works just fine, for both colors and dynamic variables.
some other things may not work in development version (1.5. is unstable) but these seem to do.

Kindly let me know if you run into any issue.
B.

**Comment by berteh** [comment]
oh no, scratch what I said: the SGAttributes did work fine in my case in 1.5.2 (for changing font business card name & titlle, and the vertical position of the background topmost wave), but indeed the colors got messed up.

Can you please check if SGAttributes are indeed not working once again? ie: is the wave moved up in the card of John Doe, and down in the card of Jane Smith?
For the font maybe it's just the font face used in the example not being installed on your machine? in that case you can either change its name in the csv, or download it for free from http://www.1001fonts.com/princess-sofia-font.html

I'll look to fix the colors bug.

**Comment by Erwinius** [comment]
Hi B.

I tried 1.5.2; thank you for suggesting this version. SGAttributes works fine. So, that's not an issue anymore. 

Like you mentioned yourself; the color bug is still present. Thanks for trying to fix the colors bug.
To add one thing I noticed with the colorbug. It seems that -if you use more then one record- only the first record will cause the problem. In your example: Blue1 became pink, but Orange stays orange.

Erwinius

PS: I've also experience problems with using ë, é, ï, ü etc. Is that issue known as well or do you like me to add an issue on this as well?

**Comment by berteh** [comment]
Hi @Erwinius, accents should not be a problem. As a matter of fact you can use the full set of UTF-8 characters. So chinese, arabic, russian, braille, maths, arrows and [much more](http://csbruce.com/software/utf-8.html) do work just fine, simply copy-paste them from a good utf-8 character table or use the appropriate keyboard combination.

Can you please make sure you save your csv as Unicode UTF-8, and re-test?
OpenOffice calc is good at generating good csv in UTF-8, Excel a bit less, or you can use a good text editor (like notepad++) to resave the csv and making sure of the encoding. Attached is a sample business card data with such accents in the 2 first names that works fine for me (just remove .txt extension that is required by github).

[Business_Card.csv.txt](https://github.com/berteh/ScribusGenerator/files/319157/Business_Card.csv.txt)

**Comment by Erwinius** [comment]
Hi,

I use an old version of Excel (2007). I suppose that's the problem. I
ll use something else. Thank you for your help.

**Comment by berteh** [comment]
maybe this (free) add-in works for you then: http://www.csvio.net/

another quick question: this script is often crashing my scribus 1.5.2 in windows (but not in ubuntu), with the following opaque error message: 
C:\Program Files\Scribus 1.5.2\python\lib\traceback.py, line 13, in _print
    file.write(str+terminator)
IOError: [Errno 9] Bad file descriptor

looks like the include python library is missing a piece or two... did you encounter the same problem (as you use windows?)

Since I mostly use Ubuntu I have difficulties solving such issues on other OS.
thanks!

**Comment by Erwinius** [comment]
Don't recognize this error. The moment it appears, I'll inform you.

**Comment by Erwinius** [comment]
Hi,

Working with 5.2 and I notice that the bugs "Dynamic Colors" & "More advanced uses" both appear and still are an issue. 

If you like me to write the issues down and describe what I'm experiencing; please let me know. I'm more than happy to do so.

Thanks!
Erwinius

PS: The CSV excel add in works great!

**Comment by berteh** [comment]
Hi @Erwinius. 
This bug should now be fixed. kindly update your ScribusGenerator to test it and let me know if this is alright for you.
B.
