### ISSUE TITLE
screencasts or animated gifs of Scribus Generator in action

### ISSUE THREAD

**Issue by luzpaz** [berteh/ScribusGenerator#5]
@berteh can you post a screencast or some animated gifs of using scribus generator and post them in the README?

**Comment by berteh** [comment]
done. added in readme. online at https://www.youtube.com/watch?v=kMsRn38TOiQ
hope this helps.

**Comment by luzpaz** [comment]
fantastic. thanks. I'll post this to the scribus mailing list

**Comment by berteh** [comment]
very kind of you.
