### ISSUE TITLE
better output numbering with leading zeros

### ISSUE THREAD

**Issue by MartinZaske** [berteh/ScribusGenerator#6]
The automatic numbering of output-files is messy and listing in a file-explorer can be fixed with leading zeros.

I have manually added zfill(3) but if a user want to mail merge 150.000 documents or whatever we need an idea to automatically add the appropriate number of digits (number of leading zeros). Please help and please put the zfill idea into the code, if you like it. Good job for having put Scribus Generator on github.

Greetings,  Martin Zaske

    def createOutputFileName(self, index, outputFileName, headerRow, row):
        # If the User has not set an Output File Name, an internal unique file name
        # will be generated which is the index of the loop.
        result = str(index)
        result = result.zfill(3)

**Comment by berteh** [comment]
good one, thanks. will implement. don't hesitate to fork/pull request to contribute to the code.
