### ISSUE TITLE
"saving PDF" popup-message is blocking computer during run of script

### ISSUE THREAD

**Issue by MartinZaske** [berteh/ScribusGenerator#64]
Dear script-whisperers,
in 2015 I had pulled a copy and made my own humble fork for special needs. Today I have come back here and I am amazed how this script has developed, respect! (I keep getting e-mails every so often, so I know this tool is very active and alive. I tried the latest version today - and it also shows my "trouble", so here is my contribution/request):

(I am a total newbie at Python, so I cannot submit my own hacks. If you are interested, the latest change I hacked, was to offer the user a box to enter an offset. So if I run several batches of the script, the numbers will not always start at 1, 2, 3 again but maybe go 201, 202, 203 and so no previous output gets overwritten. I just fear that my cody is bad and ugly and illegal and unpythonic.)

Today I come with a request for help please: As our database is growing, our exports are taking longer. (I also have to cut my runs into batches, because, depending on Scribus-file, my Scribus crashes after some 80+ runs of the (old) script. That was one reason why I invented the offset. But the crashes are solved, not the issue here.)

I notice this: every few seconds, as the script is creating yet another PDF-file, Scribus brings up a popup-window saying "saving PDF" and giving several progress bars. Those are fun, when I manually create a PDF. But when I run the script, they come all the way up and somehow grab the focus. This means that I cannot use my computer at all, while the script is running. I tried minimizing Scribus and fiddling with several screens, but the stuff is just too deep for me.

If there is a workaround, please advise. And in general, I humbly propose as a new feature to remove (maybe optional for users to chose) those endless popup-progress-windows if at all possible. Or maybe make them less agressive, if they cannot be turned off?

**Comment by berteh** [comment]
Hi Martin.
The pop-ups you mention come from scribus, not scribus generator, so there's nothing I can do about that.
Pdf export by scribus from the command-line is in the pipeline, and would I guess avoid this problem... let's see how fast it gets released. In the meanwhile I think you're better off using a single (merged) sla, as the export to multiple pdf is likely VERY time consuming... see my answer in #65 for more details.

hope this helps.
B.

**Comment by berteh** [comment]
or you can use scribus generator to create a single sla, then use the script at https://github.com/aoloe/scribus-script-repository/tree/master/to-pdf to export to pdf from the command line...that should not display that popup.

how to use this script (or any other) is explained in details in

in short download [to-pdf.py](https://github.com/aoloe/scribus-script-repository/raw/master/to-pdf/to-pdf.py) and export with the command  ```scribus -g -py to-pdf.py -- file.sla``` ... but that does not solve your issue of printing order... so I'd favor the answer in #65 

B.

**Comment by MartinZaske** [comment]
Thank you Berteh for those hints about
      workflow. Today I have another crisis (our commercial
      spell-checker is dead) but will look into it soon. Will report
      back about success.
      
      Much obliged,
      
      Martin
      
      On 10/20/2016 8:28 PM, Berteh - notifications@github.com wrote:
    
    
      or you can use scribus generator to create a single sla, then
        use the script at https://github.com/aoloe/scribus-script-repository/tree/master/to-pdf
        to export to pdf from the command line...that should not display
        that popup.
      how to use this script (or any other) is explained in details
        in
      in short download to-pdf.py
        and export with the command scribus -g -py to-pdf.py --
          file.sla ... but that does not solve your issue of
        printing order... so I'd favor the answer in #65 
      B.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/berteh/ScribusGenerator","title":"berteh/ScribusGenerator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/berteh/ScribusGenerator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@berteh in #64: or you can use scribus generator to create a single sla, then use the script at https://github.com/aoloe/scribus-script-repository/tree/master/to-pdf to export to pdf from the command line...that should not display that popup.\r\n\r\nhow to use this script (or any other) is explained in details in\r\n\r\nin short download [to-pdf.py](https://github.com/aoloe/scribus-script-repository/raw/master/to-pdf/to-pdf.py) and export with the command  ```scribus -g -py to-pdf.py -- file.sla``` ... but that does not solve your issue of printing order... so I'd favor the answer in #65 \r\n\r\nB."}],"action":{"name":"View Issue","url":"https://github.com/berteh/ScribusGenerator/issues/64#issuecomment-255204278"}}}
    
    
    
    
    -- 
courriel par Martin Zaske, membre de :

LINGO-Bénin
B.P. 48
Bassila
Rep. du Bénin

Tel. 00229 / 97.44.62.95

Organisation Non Gouvernementale
Decret No. 2001-234 du 12 juillet 2001
No. d'enregistrement 6/033/P-SG STCCD-DCDI-ONG
du 05 septembre 2012

**Comment by berteh** [comment]
closing, as to-pdf.py script does the job just fine.
feel free to re-open if needed.
