### ISSUE TITLE
insert text with HTML tags

### ISSUE THREAD

**Issue by ekleins** [berteh/ScribusGenerator#67]
Hi, 
I want to merge some fields that contain HTML tags (<em> for emphasized for example) embedded inside the text of the record. Is it possible for the script to interpret correctly the tag and render it accordingly?

**Comment by berteh** [comment]
hello. it's not yet possible, but a good idea. will look into a possible way and keep your posted.

**Comment by berteh** [comment]
Hello Eduardo.

Sorry I won't be able to implement that feature: Scribus' way to handle text decoration via [styles](https://wiki.scribus.net/canvas/Help:Manual_Styles) is way too different from inline (html or other) annotations for that to be easy.

One way around that issue, if the inner structure of elements you want to emphasize is similar over all your data records, is to apply the visual emphasis (bold & italics in the picture below) to a portion of text that includes one (or more) variable with the [Scribus Story Editor](https://wiki.scribus.net/canvas/Working_with_Story_Editor). That portion of your text will be accordingly emphasized for all data records. It will not show if the variable value is empty for a particular record ;)

![sg-richtext](https://cloud.githubusercontent.com/assets/36950/21581474/84826c6e-d033-11e6-83b3-4443487c7758.png)


If you have development skills and want to try to implement this feature feel free to fork and try, I'd be happy to have a look at your work and merge for others to enjoy it!

Happy new year!

**Comment by ekleins** [comment]
Thanks Berteh. I will try to find a way around. Sorry but I'm not a very
skilled developper.

Happy new year to you!

Saludos eks
