### ISSUE TITLE
Is there a way to display the next field on the same page?

### ISSUE THREAD

**Issue by heat4212** [berteh/ScribusGenerator#68]
First off, thanks for creating this feature! 

Is there a way to make this act more like the label mail merge in Office? Specifically, we are creating a template for our  school yearbook. We would like to create a mail merge for the student photo pages that can easily be updated every year with their new pictures and grades. I love that I can just update a .csv file and import the information along with a picture! I got that part of your script working nicely. 

But when I merge, I can only get one student displayed per page. Can I set up a table and use some sort of "next" command to call the information from the next row of my .csv file (like Word's `<<Next Record>>`)?

Thanks for your help!

**Comment by berteh** [comment]
Hello @heat4212 

Thanks for getting in touch.
Displaying multiple records on a single page, in a matrix (incl. table) or list, is something I'd love to have. It has been discussed a bit before in quite technical terms in #11.

My main problem is a problem of ergonomy: how to get the information (in scribus) of what elements to repeat (in your case the student "record" with picture and grades is maybe a table line, or a set of 2 columns if you have a layout with 2 columns of students, I guess)?

I could imagine another layout to be a succint table of all students ordered by class with their picture and name underneath the picture, in a table of 5 columns/8 lines per sheet... how would you then imagine to tell scribusgenerator "i want maximum 5 columns and maximum 8 lines per sheet"?

any idea is welcome!
happy new year!
B.

**Comment by heat4212** [comment]
Thanks for the response! I had glanced at that thread but it was a bit over my head. But once I clicked on your link for emdata I can see that you have indeed thought about and addressed this type of functionality! 

My coding experience is very small (a touch of C++ many years ago) so I can follow the logic of coding but not offer much specific input. All I can think is that mailmerge doesn't try to control the placement of data just drops it into the spot where the `<<NextRecord>>` tag is. If my document just has one page of labels in it, then I only get one page worth of records imported from my spreadsheet. I can live with that.

So maybe it's possible to bypass coding placement and table size into your script and just figuring out a way to read and import the next record on the spreadsheet? Leave it up to the user to make sure they have some version of VAR.next (or whatever the python equivalent of `<<NextRecord>>` is if that exists) placed on their original document as many times as they have records to import? (Sorry I don't know python code terminology!)

It would require a bit more set-up time than emdata but year to year would save a ton of work. In my yearbook example, you would just have to add or remove a few cells/rows based on lost or new students.

**Comment by berteh** [comment]
Love the idea of a tag such as <<NextRecord>> to enable multiple records on a single page: seems easy enough to use by a non computer/geek. Will definitely try to get this to work, just don't know when yet but I'll keep you posted, thank for the suggestion!

**Comment by heat4212** [comment]
Awesome, glad to hear it! I will keep my eye out and thanks again for your hard work!

**Comment by quarxdmz** [comment]
Hi,

I wanted to add to the discussion, how about data will have an extra field for data grouping, all data on the same group will be printed on a page and if it exceeds on a page, it will continue on another page up until that group is finished and the next data group will start on another page and so on.

**Comment by berteh** [comment]
Hello @heat4212 

the next-record feature is now available to test in the branch https://github.com/berteh/ScribusGenerator/tree/next-record
Kindly let me know how that works for you or if you see any better way to do it... or other major improvement or bug.  I'll add some documentation later... but any feedback is already welcome in the meanwhile.  Please have a look at the example: https://github.com/berteh/ScribusGenerator/blob/next-record/example/Next_Record.sla

@quarxdmz I considered your request. thanks for the suggestion. Nevertheless I discarded it as going into the logic of the data is too much for me to handle. You could (I think) easily order your data in your spreadsheet in the right order (i.e. your "group" sequence), and fill in blank lines between the group to match the amount of records you have on each page, maybe along the lines of https://productforums.google.com/forum/#!topic/docs/edA5PlQwyWs 
hope this helps.

Berteh.

**Comment by dustinandrews** [comment]
This update is exactly what I needed. Thanks! However, when I run this version I get a key error in ScribusGeneratorBackend.py: 434
                    logging.debug("loading next record" after %s"%replacements["%VAR_name%"])

Commenting this line makes the script work as expected.

**Comment by heat4212** [comment]
I am SO sorry I disappeared for a year. (My dad had a liver transplant which forced me to suddenly drop the yearbook last year... but I am back at it this year!)

Let me just say that I LOVE this feature! It worked perfectly and was very easy to use!! I am uploading my .sla file if others want to use it as a template or example. Thanks soooooo much for the update! It will make our lives easier from here on out!

[Yearbook_template.zip](https://github.com/berteh/ScribusGenerator/files/1885893/Yearbook_template.zip)

**Comment by berteh** [comment]
Hello  @heat4212 

Sad to read about the health issues of your father.

Glad you liked the feature and could use it to your satisfaction.
Thanks for your template. I added it in our Wiki for other to find:https://github.com/berteh/ScribusGenerator/wiki#yearbook

Feel free to add a screenshot or other examples if you have more!
Berteh.

**Comment by heat4212** [comment]
No worries about my dad. It was a blessing and one year later he is recovered and better than ever!

I am adding a .zip that has everything someone would need to re-create my template. (I changed my students' names and downloaded a pile of random pics to maintain privacy). 

I did notice that when I copied the original folder then moved it to create my sample that the next-record pics lost their path (though not the original pic). Does your next-record variable use relative paths?

In any case, the fix is simple. For the images that don't load:  rt-click the frame, select Get Image... make sure the path is correct, then re-paste %VAR_pic%%NEXT-RECORD% back into the File Name: field. 

Thanks again! I hope people find this example useful! @berteh , I really appreciate you taking the time to respond and customize your script!

![yearbookportraits_thumb](https://user-images.githubusercontent.com/24929631/38470663-2d45f890-3b1b-11e8-8329-f3363e4bbd17.PNG)

[YearbookPortraitsTemplate.zip](https://github.com/berteh/ScribusGenerator/files/1887735/YearbookPortraitsTemplate.zip)

**Comment by berteh** [comment]
Thanks @heat4212  for this nice addition! I update the wiki accordingly at https://github.com/berteh/ScribusGenerator/wiki#yearbook ... and glad to read your father's transplant was a success.

Indeed all pictures paths in Scribus are relative, whether you use a next record or not has no influence on it. They are actualy relative to the path of the very first image in the current document, as far as I understood it from the lack of documentation.

B.
