### ISSUE TITLE
not ever CSV-file is separated by commas...

### ISSUE THREAD

**Issue by MartinZaske** [berteh/ScribusGenerator#7]
Hello, in our data-files we typically cannot use commas nor semi-colons for delimiters, because they feature as part of our data.

So I am using a private delimiter. (If you are curious, I am using '#' but that does not matter).

So I have manually enhanced the code like this, to allow me to set my personal delimiter:

    def getCsvData(self, csvfile):
        # Read CSV file and return  2-dimensional list containing the data
        reader = csv.reader(file(csvfile), delimiter='#') # set your personal delimiter in this line
        result = []
        for row in reader:
            rowlist = []
            for col in row:
                rowlist.append(col)
            result.append(rowlist)
        return result

I hope to write a version, where the GUI will ask the user, what delimiter he wants to use (while proposing the good ole comma)

Please integrate the choice of delimiter into the script, if you like the idea (because it took me a long time to read the script and find the command csv.reader and to look up the syntax re delimiter...

greetings and good job,

Martin Zaske

**Comment by berteh** [comment]
will integrate in next refactoring with command line support. thanks for the report.
