### ISSUE TITLE
Running from GUI steals focus for each PDF saved

### ISSUE THREAD

**Issue by dagoss** [berteh/ScribusGenerator#71]
While running ScribusGenerator from within Scribus, every time a PDF is saved, the window that opens steals focus (on Windows). When running for about 1500 records, I basically couldn't use my computer for an hour, because I'd lose window focus every few seconds.

**Comment by berteh** [comment]
Sorry to read that is was so painful !  I recommend generating a single pdf (simply clicking "merge" in ScribusGenerator) and then splitting the resulting pdf using something like the open source [pdf split and merge](www.pdfsam.org).  That will be _much_ faster as well (I guess about 2-3 minutes in total).

Nevertheless I understand it's an issue and will look into it for a later release. If you want to propose a code pull that fixes this don't hesitate !

**Comment by berteh** [comment]
also see #64 for 2 good workarounds... as this dialog that bothers you is actually created by Scribus itself and not the Generator.

I'll try to find a workaround that can be integrated into this script, but not likely soon... so If you want to propose a code piece to fix it you're more than welcome !

**Comment by dagoss** [comment]
Thanks for the response and for the tip. I needed all the files named a specific way, which I already had in the data file, and ScribusGenerator is surprisingly the only data merge tool that actually supported having the output filename in the data file (neither InDesign or Word do that!). Had I anticipated this issue, I might have done as you suggested and tried splitting and renaming as a post-processing step instead. Of course, once the data merge was running, I felt committed to see it to the end :)

I'll close this issue though because it's definitely a duplicate of #64 (sorry!)
