### ISSUE TITLE
Only first attribute is applied

### ISSUE THREAD

**Issue by dustinandrews** [berteh/ScribusGenerator#72]
When I to set two items in a text box, only the first one listed is working.
Run the attached (with next_var code) and examine the big text boxes. They should have the same fontsize and seperation, but whichever attribute is first is the only one applied.

[3x4cards.zip](https://github.com/berteh/ScribusGenerator/files/870321/3x4cards.zip)

**Comment by berteh** [comment]
looking into it. could you please send me the "template" scribus file, before the data merge?

**Comment by berteh** [comment]
Hi @dustinandrews 

This bug is now fixed, thanks for the catch ! Could you please check if it works for you?

Attached my test with a subset of your data and simplified card view. In my tests the linespacing was stored either in <para> or <trail> element... so I created a SGAttribute for both: better safe than sorry ;)
[GameCards_dustinandrews.zip](https://github.com/berteh/ScribusGenerator/files/871095/GameCards_dustinandrews.zip)

Would if be ok with you if I uploaded this subset of your first 25 cards as an additional example in the ScribusGenerator example folder?

**Comment by dustinandrews** [comment]
Thanks! I'm looking forward to trying it out. if you will as this as record #1 before you post it, I would appreciate it.


,License, CC 3.0-unported, MonsterCards is based on the open source work of Sage LaTorra and Adam Koebel. This work is licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA. Additionally the MonsterCards.PDF file and card contents themselves are created by Dustin Andrews and licensed under the Creative Commons Attribution 3.0 Unported License. Thanks to https://www.reddit.com/u/kotaman for putting the official monsters into a spreadsheet. https://docs.google.com/spreadsheets/d/10EOTtXe8x7ZCxq6WVlLSeAFeZ4FGjt3i-rn2e6U4zpY/edit?usp=sharingAnd  https://www.reddit.com/user/MilesZS for putting them into JSON. https://github.com/mileszs/dungeon-world-data,,,,,,,,,,,,,,,


I wonder if you know offhand if you can detect overflowed textboxes from the python?



-Dustin
--
<http://www.kickstarter.com/projects/988159748/extracore-arduino-compatible>\o/ \o/ \(;,,,; )/ \o/ \o/<http://bit.ly/1bQPEX2>
________________________________

**Comment by berteh** [comment]
Sure for the license text. Maybe I'll then add some color too (per monster type), as it would look nicer on cards.

About the overflow: afaik not from Python. I quite liked your way to handle it by adapting the font size to the description length! FYI using a linespacing 0.5pt smaller than the description font size results in more compact but still readable.

In the meanwhile you can create the SLA with the Scribus Generator, and the Scribus GUI will automatically warn you of overflows (and highlight them ;) on pdf export.

**Comment by berteh** [comment]
added (with colors, I hope you don't mind) in https://github.com/berteh/ScribusGenerator/blob/master/example/MonsterCards/LICENSE.md
and mentioned in https://github.com/berteh/ScribusGenerator#multiple-records-on-a-single-page

Let me know if you need me to change anything, and thanks for the help !
