### ISSUE TITLE
Content shifted down with --merge option

### ISSUE THREAD

**Issue by PlasmaBinturong** [berteh/ScribusGenerator#79]
Hi, thanks for ScribusGenerator, it's really great.

I have a problem however when using `ScribusGeneratorCLI.py` with the `--merge` option:
in the output .sla document, the page content is shifted down at every new page. So in the end only the first page has its content properly centered in the page...

Is there some option for the position of the scribus objects from the template that I am missing?

Thanks in advance!

**Comment by PlasmaBinturong** [comment]
Indeed, I had to set the correct size in the document properties (A5) (the pages were already at the right size, not the document).

**Comment by berteh** [comment]
this is indeed fixed by setting the document properties to the right page size. thanks.
(reason is explained in #46 if you want more details)
