### ISSUE TITLE
CLI Windows 10 Command line

### ISSUE THREAD

**Issue by jvr14115** [berteh/ScribusGenerator#82]
I am not an expert at all with python scripts or using command line.
I have tried many ways to get ScribusGeneratorCLI to run from command line.
The only result I get is that it opens the CLI script.
What am I doing wrong?

I have Scribus 1.4.6, Windows 10 (x86)

Thanks in advance!

**Comment by jvr14115** [comment]
Solved: needed to change python as default program for .py files. (Was set on Notepad).

**Comment by berteh** [comment]
glad you solved it. hope you like it.
