### ISSUE TITLE
barcode 

### ISSUE THREAD

**Issue by hiousi** [berteh/ScribusGenerator#86]
Hi,

Not an issue, more a question about a feature.
I am so happy to have discovered ScribusGenerator, it is so powerfull,  I like the fact that it can be called from command line. I think it will become the center of my label printing workflow.

I am looking for a way to handle barcodes with scribus generator.
I have 300 labels to generate, each of them will contain a unique barcode. I'm using Scribus 1.5.2 and ScribusGenerator from git.

I'm new to Scribus + generator. I have no real solution for now to do what I want, I have thought about using things like:

- use scribus attribute and native sribus barcode feature (not sure it is possible)
- embeding some postscript code in sla template and let bwipp render the barcode (possible?)
- first, generate images (one for each barcode) with an external program. Then, use ScribusGenerator to replace the template barcode (may sound complicated, but should work, performance need to be tested)
- write a python script to generate the barcode "on the fly", and make it work with scribus generator 

you may think of some other ways. thanks for your help

**Comment by berteh** [comment]
Hello @hiousi , sorry for the late reply, I got no notification for this issue, don't know why.

I'm not familiar enough with python and the barcode generators libraries to know how well they would interact "live" with Scribus... and therefore I'd personnally go with the option to generate all your barcodes as images (preferably vector: eps or pdf) in a given folder, and simply include them as image frames, providing the image name as a variable to be used by SG in your CSV data.

Seems easy enough... but kindly let me know what way you tried and or chose !
B.

**Comment by hiousi** [comment]
That what I have done!
thanks
