### ISSUE TITLE
how to output PDF via command line?

### ISSUE THREAD

**Issue by gree303** [berteh/ScribusGenerator#87]
So far everything works great. The only thing I can't get is PDF export from command line. It's only generating .SLA files. Is there any easy way of getting PDF's?

thanks - keep up the awesome work!

**Comment by gree303** [comment]
Update: ..based on some suggestions from the #scribus irc channel.
Using to-pdf.py + scribus 1.5.x version
[https://github.com/aoloe/scribus-script-repository](https://github.com/aoloe/scribus-script-repository)

**Comment by jvr14115** [comment]
Not sure how this would help me.
I am no expert in scripting. I do manage to run scribusgeneratorcli from a shell commandline.
Now I need to find a way to save or convert those files (100's) to pdf. Using the pdf settings I gave to the .sla template.
Could you ( or anyone) explain how to use this to-pdf.py?
I get a "no module named scribus" error.

**Comment by berteh** [comment]
Hello jvr.
This error means the command you use to run the to-pdf.py script does not load the scribus python module.

To run a scribus script check out 
* The Scribus manual: https://www.scribus.net/svn/Scribus/trunk/Scribus/doc/en/scripter1.html  to run it from within Scribus
* The Scribus Wiki: https://wiki.scribus.net/canvas/Command_line_scripts  to run it from command line

You would then need to "feed" the sla name files to this to-pdf script...  or (maybe simpler in your case) to modify it so you give it a folder name, and it transforms all SLA files in that folder into PDF.

**Comment by jvr14115** [comment]
Hi Berteh,
I am totally lost here.
I have no clue on how to work with python. Hope you can help.
I need a simple way to convert a .sla to a .pdf without running scribus (or only in background).
scribus,exe is in path a, the .sla in path b. Is there a script that I could run from windows or python command?

**Comment by berteh** [comment]
following works for me, when run from the Windows command line, after I copied the "to-pdf.py" script in the Scribus program folder (could be located elsewhere too). PDF is generated in the folder of the SLA source file, with same name.

C:\Program Files\Scribus 1.5.3>Scribus.exe -g -py to-pdf.py -- D:\test\t.sla

script file is at https://raw.githubusercontent.com/aoloe/scribus-script-repository/master/to-pdf/to-pdf.py

**Comment by berteh** [comment]
btw: no need to install Python, the library is included in scribus.

**Comment by RidaAyed** [comment]
> C:\Program Files\Scribus 1.5.3>Scribus.exe -g -py to-pdf.py -- D:\test\t.sla
The `--` is crucial :+1:

**Comment by mara004** [comment]
For any readers of this thread, possibly [`sla2pdf`](https://github.com/sla2pdf-team/sla2pdf) might interest you?
