### ISSUE TITLE
Blank line in data file breaks script

### ISSUE THREAD

**Issue by dagoss** [berteh/ScribusGenerator#90]
If a data file has a blank line in it, the ScribusGenerator chokes with a bunch of error messages and does not generate any files. This could happen (as it just happened to me) if there is a blank line at the end of a file.

It would be great if the script checked if the line was completely empty before splitting it, to avoid errors like this.

**Comment by berteh** [comment]
problem confirmed. and it's indeed annoying depending on how your CSV data is created. Will try to fix this in the next release. If you already have code that fix this feel free to submit a pull request!

(sorry for huge delay in my answer, i missed this issue completely in GitHub)
Berteh.

**Comment by berteh** [comment]
took some time, but this should now be fixed. kindly test after updating Scribus Generator, and thanks for your patience.
