### ISSUE TITLE
Add metainfo.xml

### ISSUE THREAD

**Issue by luyatshimbalanga** [berteh/ScribusGenerator#91]
I prepared a file named metainfo.xml which allow to [Gnome Software](https://www.wikiwand.com/en/GNOME_Software) to view it as add-on based on the [Appstream add-on guideline](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Addon.html) and the [short version](https://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Addons.html)

Simply download the [metainfo.xml](https://luya.fedorapeople.org/appdata/scribus-generator.metainfo.xml) and feel free to make the necessary change.

**Comment by berteh** [comment]
thanks. added to the wiki: https://github.com/berteh/ScribusGenerator/wiki/Gnome-software-shortcut
