### ISSUE TITLE
Command line pdf

### ISSUE THREAD

**Issue by jvr14115** [berteh/ScribusGenerator#93]
I'm using SG to generate 100s of pdf's on a daily base.
Now I need to find a sollution that can do this from command line.
The process is activated from a VBA macro and should run in the background.

I manage to activate the ScribusGeneratorCLI which creates the .sla files (very fast!)
How to best convert all these files to pdf (using all the settings I have set in the .sla template)?
I read something about to-pdf.py, but I do not get how to run that in combination with the ScribusGeneratorCLI.

Help needed urgently!
Thanks

**Comment by berteh** [comment]
Hello jvr. Happy to read this tool is useful to you.

The command you use to run the to-pdf.py script does not load the scribus python module.

To run a scribus script check out 
* The Scribus manual: https://www.scribus.net/svn/Scribus/trunk/Scribus/doc/en/scripter1.html  to run it from within Scribus
* The Scribus Wiki: https://wiki.scribus.net/canvas/Command_line_scripts  to run it from command line

You would then need to "feed" the sla name files to this to-pdf script...  or (maybe simpler in your case) to modify it so you give it a folder name, and it transforms all SLA files in that folder into PDF.

**Comment by berteh** [comment]
Needless to say (but maybe it's usefull anyway): Scribus needs to be installed on the machine that runs to-pdf.py   (whereas ScribusGeneratorCLI does not need Scribus per se.)

Sorry I have no clue about VBA, or how VBA sets the python environment and modules path when it calls a command to further help on this particular issue.

... and the pdf generation may take A WHILE if not done efficiently (for instance if you run the script from scratch for each pdf). You may consider a way to generate all pdfs from within a single Scribus session, to save on program open+close time.

Kindly keep me updated with the solution you come up with, as I'm pretty sure other might be interested.

FYI my current workaround to Scribus being so slow at generating PDFs from command line is to generate my documents in "merged" SLA mode, generate a single PDF with all of the needed content, and split the pdf with a command-line tool like pdf-tk.  It's a bit more problematic if your generated documents don't have the same number of pages... but even there workarounds are possible.

Let me know if you wanna discuss this other workflow in more details. I've explained it shortly in https://github.com/berteh/ScribusGenerator/issues/65#issuecomment-255195253

**Comment by jvr14115** [comment]
Thanks for your comments Berteh
Running ScribusGeneratorCLI from vba is actually quite simple. It pushes a string to the windows command:

Call Shell([path to python] [path to script] [arguments] [path to template])

in my case: 

Call Shell (C:\Python27\python.exe C:\Scribus\Scripts\ScribusGeneratorCLI.py -n %VAR_FileName% C:\Scribus\Template.sla)

Various people are updating data in excel tables. I created a VBA macro that creates csv files from this data and pushes the creation of .sla files whenever the Excel file is saved. Of course it requires Scribus and python to be installed, but the users never have to actually work in it.
Only missing link is the automatic generation of pdf's.

Unfortunately I have no clue about Python scripting so far have not even been able to convert a single sla into pdf using pdf-to.py. No idea what I am doing wrong.

**Comment by jvr14115** [comment]
Hi Berteh
It seems that to create pdf's I need to open scribus. Using -g paramer I can push the process to the background.

Instead of working on a script that loops through all created sla documents and turn the into pdf, I would consider to just run the "regular" SG instead of SGCLI.
Would there be a way to fix the arguments in the SG script?

**Comment by berteh** [comment]
See detailed explanation at https://github.com/berteh/ScribusGenerator/issues/87#issuecomment-346932881

Hope this works for you, if not feel free to come back for more explanations.

**Comment by jvr14115** [comment]
Hi Berteh,

the "to-pdf.py" concept is working fine. it is pretty slow but ok...
do you know if there is anyway to run the to-pdf-py script in background. Now scribus keeps popping up which is annoying, looks very unprofessional and doesnt allow the user to use the computer for anything else.

**Comment by mara004** [comment]
For any readers of this thread, possibly [sla2pdf](https://github.com/sla2pdf-team/sla2pdf) might interest you?

**Comment by berteh** [comment]
most useful, thanks.
